PRAGMA foreign_keys = ON;

-- Motor profesional independiente para diseños de estampas de remeras.
INSERT OR IGNORE INTO service_definitions (
  id,service_type,name,description,version,enabled,suggestions_enabled,default_strategy,
  created_at,updated_at
) VALUES (
  'service-print-design','print-design','Diseño de estampas',
  'Diseño de estampas para remeras, con preparación para DTF y sublimación.',
  1,1,1,'balanced',strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')
);

INSERT OR IGNORE INTO pricing_engines (
  id,engine_key,name,description,engine_type,category_id,calculator_key,
  service_definition_id,unit_kind,tags_json,status,classification_origin,
  classification_confidence_micros,classification_explanation,is_system,created_at,updated_at
) VALUES (
  'engine-print-design','print-design','Diseño de estampas',
  'Presupuestos profesionales para diseñar estampas de remeras.',
  'service','category-design','professional-service-v1','service-print-design','project',
  '["diseño gráfico","estampas","remeras","dtf","sublimación","vectorización"]',
  'active','automatic',1000000,'Motor de diseño de estampas incorporado por el sistema.',1,
  strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')
);

INSERT OR IGNORE INTO service_parameters (
  id,service_definition_id,parameter_key,name,label,parameter_type,description,
  required,sort_order,enabled,suggestion_enabled,is_system,ui_managed,created_at,updated_at
) VALUES
('pd-client-type','service-print-design','clientType','Tipo de cliente','Tipo de cliente','single_select','Contexto comercial del encargo.',0,10,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-brief','service-print-design','briefDescription','Descripción del pedido','Descripción breve del pedido','text','Resumen de lo solicitado por el cliente.',0,20,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-main-work','service-print-design','mainWorkType','Tipo principal','Tipo principal de trabajo','single_select','Elegí la intervención principal del encargo.',1,30,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-operations','service-print-design','additionalOperations','Operaciones adicionales','Operaciones adicionales','multi_select','Marcá todas las tareas adicionales necesarias.',0,40,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-complexity','service-print-design','complexity','Complejidad','Nivel de complejidad general','single_select','Valoración profesional global; no reemplaza el detalle de tareas.',1,50,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-input-quality','service-print-design','inputQuality','Calidad recibida','Calidad del archivo recibido','single_select','Estado general del material entregado.',0,60,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-input-conditions','service-print-design','inputConditions','Condiciones recibidas','Problemas o características del archivo','multi_select','Detalles verificables del material original.',0,70,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-background-level','service-print-design','backgroundLevel','Eliminación de fondo','Nivel de eliminación de fondo','single_select','Dificultad del recorte necesario.',0,80,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-background-details','service-print-design','backgroundDetails','Detalles de fondo','Detalles del recorte','multi_select','Elementos que hacen más delicado el recorte.',0,90,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-restoration-level','service-print-design','restorationLevel','Limpieza y restauración','Nivel de limpieza / restauración','single_select','Intervención necesaria para recuperar la imagen.',0,100,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-restoration-tasks','service-print-design','restorationTasks','Tareas de restauración','Tareas de limpieza / restauración','multi_select','Trabajos concretos de reparación.',0,110,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-vector-level','service-print-design','vectorizationLevel','Vectorización','Nivel de vectorización / redibujo','single_select','Tipo de conversión o reconstrucción vectorial.',0,120,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-vector-count','service-print-design','vectorizationElementCount','Elementos a vectorizar','Cantidad aproximada de elementos a vectorizar','number','Cantidad estimada de piezas o componentes.',0,130,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-vector-features','service-print-design','vectorizationFeatures','Detalles vectoriales','Características de la vectorización','multi_select','Contenido y exigencias del redibujo.',0,140,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-vector-editable','service-print-design','deliverEditableVector','Vector editable','Entregar archivo vectorial editable','boolean','Entrega adicional del vector editable.',0,150,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-composition-level','service-print-design','compositionLevel','Composición','Nivel de composición del diseño','single_select','Complejidad del armado visual.',0,160,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-composition-count','service-print-design','compositionElementCount','Elementos a integrar','Cantidad de elementos a integrar','number','Cantidad aproximada de componentes de la composición.',0,170,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-composition-features','service-print-design','compositionFeatures','Detalles de composición','Características de la composición','multi_select','Recursos y técnicas del armado.',0,180,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-ai-level','service-print-design','aiLevel','Trabajo con IA','Nivel de trabajo con IA','single_select','Alcance de la asistencia o generación con IA.',0,190,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-ai-actions','service-print-design','aiActions','Acciones con IA','Acciones con IA','multi_select','Operaciones previstas con herramientas de IA.',0,200,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-ai-count','service-print-design','aiGenerationCount','Intentos de IA','Cantidad de intentos o generaciones estimadas','number','Cantidad aproximada de pruebas antes de elegir.',0,210,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-type-level','service-print-design','typographyLevel','Trabajo tipográfico','Nivel de trabajo tipográfico','single_select','Dificultad del tratamiento de texto.',0,220,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-type-actions','service-print-design','typographyActions','Acciones tipográficas','Acciones tipográficas','multi_select','Operaciones necesarias sobre textos y fuentes.',0,230,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-color-level','service-print-design','colorLevel','Ajustes de color','Nivel de ajustes de color','single_select','Alcance de la corrección o adaptación cromática.',0,240,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-color-actions','service-print-design','colorActions','Acciones de color','Acciones de color','multi_select','Variantes y correcciones cromáticas requeridas.',0,250,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-print-output','service-print-design','printOutput','Salida para estampado','Tipo de salida para estampado','multi_select','Podés preparar DTF, sublimación o ambas salidas.',0,260,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-print-actions','service-print-design','printActions','Preparación final','Acciones de preparación final','multi_select','Controles y archivos finales para imprimir.',0,270,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-width','service-print-design','finalWidth','Ancho final','Ancho final','number','Medida final según la unidad seleccionada.',0,280,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-height','service-print-design','finalHeight','Alto final','Alto final','number','Medida final según la unidad seleccionada.',0,290,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-unit','service-print-design','dimensionUnit','Unidad','Unidad de medida','single_select','Unidad usada para ancho y alto.',0,300,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-resolution','service-print-design','finalResolution','Resolución','Resolución final · DPI','number','Resolución preparada para la salida final.',0,310,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-format','service-print-design','deliveryFormat','Formato de entrega','Formato de entrega final','single_select','Formato principal entregado al cliente.',0,320,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-halftone-level','service-print-design','halftoneLevel','Semitono','Nivel de semitono','single_select','Alcance del tratamiento de semitono.',0,330,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-halftone-details','service-print-design','halftoneDetails','Detalles de semitono','Detalles de semitono','multi_select','Adaptaciones y controles del semitono.',0,340,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-resource-level','service-print-design','resourceSearchLevel','Búsqueda de recursos','Nivel de búsqueda de recursos','single_select','Amplitud de la investigación visual.',0,350,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-resource-types','service-print-design','resourceTypes','Tipos de recursos','Tipos de recursos a buscar','multi_select','Materiales externos necesarios.',0,360,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-resource-count','service-print-design','resourceCount','Cantidad de recursos','Cantidad aproximada de recursos a buscar','number','Cantidad estimada de recursos externos.',0,370,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-element-band','service-print-design','elementCountBand','Cantidad de elementos','Cantidad de elementos a trabajar','single_select','Factor descriptivo de complejidad.',0,380,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-proposals','service-print-design','initialProposals','Propuestas','Propuestas iniciales incluidas','single_select','Cantidad de conceptos iniciales incluidos.',0,390,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-revisions','service-print-design','includedRevisions','Revisiones','Cantidad de revisiones incluidas','single_select','Rondas de corrección incluidas.',0,400,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-extra-revisions','service-print-design','hasExtraRevisions','Revisiones extra','Puede haber revisiones extra','boolean','Indica si se contemplan revisiones fuera del alcance.',0,410,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-extra-revision-value','service-print-design','extraRevisionValue','Valor revisión extra','Valor de cada revisión extra','currency','Importe informativo; no se suma sin indicar una cantidad real.',0,420,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-variant-level','service-print-design','variantLevel','Variantes','Cantidad de variantes','single_select','Variantes del mismo diseño.',0,430,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-variant-types','service-print-design','variantTypes','Tipos de variante','Tipos de variante','multi_select','Cambios que diferencian las variantes.',0,440,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-locations','service-print-design','printLocations','Ubicaciones','Tamaños / ubicaciones de impresión','multi_select','Ubicaciones y públicos de las salidas finales.',0,450,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-size-count','service-print-design','finalSizeCount','Tamaños finales','Cantidad de tamaños finales a entregar','number','Cantidad total de medidas finales.',0,460,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-editable','service-print-design','editableDelivery','Entrega de editable','Entrega de archivo editable','single_select','Adicional independiente; no se cobra automáticamente sin una regla.',0,470,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-urgency','service-print-design','urgency','Urgencia','Urgencia del trabajo','single_select','Prioridad solicitada; preparada para una regla futura.',1,480,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-origin','service-print-design','designOrigin','Origen','Origen del diseño','single_select','Punto de partida entregado por el cliente.',1,490,1,0,1,0,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pd-hours','service-print-design','estimatedHours','Tiempo estimado','Tiempo estimado del trabajo','number','Se carga como horas y minutos; el motor lo conserva en horas decimales.',0,500,1,0,1,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now'));

INSERT OR IGNORE INTO parameter_options (id,parameter_id,label,value,sort_order,enabled,created_at,updated_at) VALUES
('pdct-particular','pd-client-type','Particular','individual',10,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdct-venture','pd-client-type','Emprendimiento','venture',20,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdct-small','pd-client-type','Marca pequeña','small-brand',30,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdct-medium','pd-client-type','Marca mediana','medium-brand',40,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdct-other','pd-client-type','Otro','other',50,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdmw-bg-simple','pd-main-work','Quitar fondo simple','background-simple',10,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdmw-bg-complex','pd-main-work','Quitar fondo complejo','background-complex',20,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdmw-clean','pd-main-work','Limpieza de imagen','image-cleaning',30,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdmw-vector-basic','pd-main-work','Vectorización básica','vector-basic',40,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdmw-vector-manual','pd-main-work','Vectorización corregida manualmente','vector-corrected',50,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdmw-redraw-partial','pd-main-work','Redibujo parcial','redraw-partial',60,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdmw-redraw-full','pd-main-work','Redibujo completo','redraw-full',70,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdmw-comp-simple','pd-main-work','Composición simple','composition-simple',80,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdmw-comp-medium','pd-main-work','Composición media','composition-medium',90,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdmw-comp-complex','pd-main-work','Composición compleja','composition-complex',100,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdmw-scratch','pd-main-work','Diseño desde cero','design-from-scratch',110,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdmw-adapt','pd-main-work','Adaptación de diseño existente','adapt-existing',120,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdmw-restore','pd-main-work','Restauración / reconstrucción de imagen','restore-image',130,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdmw-ai-gen','pd-main-work','Generación con IA','ai-generation',140,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdmw-ai-edit','pd-main-work','Edición de imagen generada con IA','ai-image-edit',150,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdmw-print','pd-main-work','Preparación final para estampado','print-preparation',160,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdop-bg','pd-operations','Eliminar fondo','remove-background',10,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdop-edges','pd-operations','Limpiar bordes','clean-edges',20,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdop-reconstruct','pd-operations','Reconstruir partes faltantes','reconstruct-missing',30,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdop-sharp','pd-operations','Corregir resolución / nitidez','fix-resolution',40,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdop-adjust-color','pd-operations','Ajustar colores','adjust-colors',50,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdop-change-color','pd-operations','Cambiar colores','change-colors',60,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdop-bw','pd-operations','Pasar a blanco y negro','black-white',70,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdop-black-shirt','pd-operations','Crear versión para remera negra','black-shirt-version',80,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdop-white-shirt','pd-operations','Crear versión para remera blanca','white-shirt-version',90,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdop-color-shirt','pd-operations','Crear versión para remera de color','color-shirt-version',100,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdop-add-text','pd-operations','Agregar texto','add-text',110,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdop-recreate-text','pd-operations','Recrear texto / tipografía','recreate-text',120,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdop-find-font','pd-operations','Buscar tipografía similar','find-similar-font',130,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdop-vector','pd-operations','Vectorizar','vectorize',140,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdop-redraw','pd-operations','Redibujar','redraw',150,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdop-compose','pd-operations','Armar composición','compose',160,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdop-search','pd-operations','Buscar elementos externos','search-elements',170,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdop-ai-gen','pd-operations','Generar imagen con IA','generate-ai',180,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdop-ai-improve','pd-operations','Mejorar imagen con IA','improve-ai',190,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdop-inpaint','pd-operations','Inpainting / relleno con IA','inpainting',200,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdop-dtf','pd-operations','Preparar para DTF','prepare-dtf',210,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdop-sublimation','pd-operations','Preparar para sublimación','prepare-sublimation',220,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdop-halftone','pd-operations','Aplicar semitono','apply-halftone',230,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdop-mockup','pd-operations','Crear mockup simple','simple-mockup',240,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdop-versions','pd-operations','Exportar varias versiones','export-versions',250,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdop-editable','pd-operations','Entregar editable','deliver-editable',260,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdc-basic','pd-complexity','Básico','basic',10,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdc-medium','pd-complexity','Medio','medium',20,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdc-high','pd-complexity','Alto','high',30,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdc-premium','pd-complexity','Premium','premium',40,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdi-excellent','pd-input-quality','Excelente','excellent',10,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdi-good','pd-input-quality','Buena','good',20,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdi-regular','pd-input-quality','Regular','regular',30,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdi-bad','pd-input-quality','Mala','bad',40,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdi-very-bad','pd-input-quality','Muy mala','very-bad',50,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdic-large','pd-input-conditions','Archivo grande y limpio','large-clean',10,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdic-medium-res','pd-input-conditions','Resolución media','medium-resolution',20,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdic-low-res','pd-input-conditions','Baja resolución','low-resolution',30,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdic-pixel','pd-input-conditions','Imagen pixelada','pixelated',40,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdic-blur','pd-input-conditions','Imagen borrosa','blurry',50,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdic-compressed','pd-input-conditions','Imagen comprimida','compressed',60,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdic-dirty-bg','pd-input-conditions','Fondo sucio','dirty-background',70,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdic-hard-edges','pd-input-conditions','Bordes difíciles','hard-edges',80,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdic-fine','pd-input-conditions','Pelos / transparencias / humo / detalles finos','fine-details',90,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdic-cut','pd-input-conditions','Partes cortadas','cropped-parts',100,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdic-reconstruct','pd-input-conditions','Requiere reconstrucción','needs-reconstruction',110,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdbl-none','pd-background-level','No requiere','none',10,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdbl-simple','pd-background-level','Fondo simple','simple',20,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdbl-medium','pd-background-level','Fondo medio','medium',30,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdbl-complex','pd-background-level','Fondo complejo','complex',40,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdbl-very','pd-background-level','Fondo muy complejo','very-complex',50,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdbd-product','pd-background-details','Producto simple','product',10,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdbd-person','pd-background-details','Persona','person',20,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdbd-hair','pd-background-details','Pelo / cabello','hair',30,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdbd-beard','pd-background-details','Barba','beard',40,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdbd-transparent','pd-background-details','Transparencias','transparency',50,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdbd-smoke','pd-background-details','Humo','smoke',60,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdbd-shadows','pd-background-details','Sombras complicadas','shadows',70,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdbd-details','pd-background-details','Bordes con muchos detalles','detailed-edges',80,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdbd-mixed','pd-background-details','Fondo mezclado con el sujeto','mixed-background',90,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdbd-fine-clean','pd-background-details','Requiere limpieza manual fina','fine-cleaning',100,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdbd-rebuild','pd-background-details','Requiere reconstrucción después del recorte','rebuild-after-cutout',110,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdrl-none','pd-restoration-level','No requiere','none',10,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdrl-light','pd-restoration-level','Leve','light',20,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdrl-medium','pd-restoration-level','Media','medium',30,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdrl-high','pd-restoration-level','Alta','high',40,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdrl-very','pd-restoration-level','Muy alta','very-high',50,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdrt-stains','pd-restoration-tasks','Quitar manchas','remove-stains',10,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdrt-noise','pd-restoration-tasks','Quitar ruido','remove-noise',20,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdrt-objects','pd-restoration-tasks','Quitar objetos','remove-objects',30,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdrt-edges','pd-restoration-tasks','Corregir bordes','fix-edges',40,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdrt-alpha','pd-restoration-tasks','Corregir transparencia','fix-transparency',50,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdrt-missing','pd-restoration-tasks','Reconstruir zonas faltantes','reconstruct-areas',60,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdrt-light','pd-restoration-tasks','Corregir iluminación','fix-lighting',70,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdrt-contrast','pd-restoration-tasks','Corregir contraste','fix-contrast',80,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdrt-legibility','pd-restoration-tasks','Mejorar legibilidad','improve-legibility',90,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdrt-repair','pd-restoration-tasks','Reparar imagen deteriorada','repair-damaged',100,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdvl-none','pd-vector-level','No requiere','none',10,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdvl-auto','pd-vector-level','Vectorización básica automática','basic-auto',20,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdvl-manual','pd-vector-level','Vectorización con corrección manual','manual-correction',30,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdvl-advanced','pd-vector-level','Vectorización avanzada','advanced',40,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdvl-partial','pd-vector-level','Redibujo vectorial parcial','redraw-partial',50,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdvl-full','pd-vector-level','Redibujo vectorial completo','redraw-full',60,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdvf-text','pd-vector-features','Incluye texto','text',10,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdvf-logo','pd-vector-features','Incluye logo','logo',20,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdvf-illustration','pd-vector-features','Incluye ilustración','illustration',30,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdvf-character','pd-vector-features','Incluye personaje','character',40,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdvf-rebuild','pd-vector-features','Requiere reconstrucción manual','manual-reconstruction',50,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdvf-match','pd-vector-features','Igualar el original lo más posible','match-original',60,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdcl-none','pd-composition-level','No requiere','none',10,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdcl-simple','pd-composition-level','Composición simple','simple',20,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdcl-medium','pd-composition-level','Composición media','medium',30,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdcl-complex','pd-composition-level','Composición compleja','complex',40,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdcf-text','pd-composition-features','Incluye texto','text',10,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdcf-images','pd-composition-features','Incluye varias imágenes','multiple-images',20,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdcf-effects','pd-composition-features','Incluye efectos','effects',30,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdcf-textures','pd-composition-features','Incluye texturas','textures',40,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdcf-background','pd-composition-features','Incluye fondo','background',50,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdcf-blending','pd-composition-features','Incluye fusión de imágenes','image-blending',60,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdcf-ai','pd-composition-features','Incluye integración con IA','ai-integration',70,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdcf-scratch','pd-composition-features','Requiere armado visual desde cero','visual-from-scratch',80,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdai-none','pd-ai-level','No requiere','none',10,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdai-simple','pd-ai-level','IA simple','simple',20,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdai-medium','pd-ai-level','IA media','medium',30,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdai-advanced','pd-ai-level','IA avanzada','advanced',40,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdaa-scratch','pd-ai-actions','Generar imagen desde cero','generate-from-scratch',10,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdaa-support','pd-ai-actions','Generar elementos de apoyo','support-elements',20,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdaa-fix','pd-ai-actions','Arreglar imagen dañada','repair-image',30,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdaa-extend','pd-ai-actions','Extender imagen','extend-image',40,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdaa-inpaint','pd-ai-actions','Inpainting','inpainting',50,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdaa-background','pd-ai-actions','Cambiar fondo','change-background',60,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdaa-style','pd-ai-actions','Cambiar estilo','change-style',70,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdaa-variant','pd-ai-actions','Crear variante','create-variant',80,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdaa-mix','pd-ai-actions','Mezclar varias referencias','mix-references',90,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdaa-tests','pd-ai-actions','Generar varias pruebas antes de elegir','multiple-tests',100,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdaa-ps','pd-ai-actions','Retoque posterior en Photoshop','photoshop-retouch',110,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdaa-ai','pd-ai-actions','Vectorización posterior en Illustrator','illustrator-vector',120,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdtl-none','pd-type-level','No requiere','none',10,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdtl-simple','pd-type-level','Texto simple','simple',20,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdtl-adjust','pd-type-level','Texto con ajuste','adjusted',30,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdtl-search','pd-type-level','Texto con búsqueda de tipografía','font-search',40,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdtl-lettering','pd-type-level','Recreación de lettering','lettering',50,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdtl-advanced','pd-type-level','Tratamiento tipográfico avanzado','advanced',60,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdta-write','pd-type-actions','Escribir texto','write',10,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdta-correct','pd-type-actions','Corregir texto','correct',20,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdta-curve','pd-type-actions','Curvar texto','curve',30,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdta-spacing','pd-type-actions','Ajustar espaciado','spacing',40,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdta-recreate','pd-type-actions','Recrear texto existente','recreate',50,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdta-source','pd-type-actions','Buscar fuente similar','find-font',60,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdta-combine','pd-type-actions','Combinar texto con imagen','combine-image',70,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdta-curves','pd-type-actions','Pasar texto a curvas','convert-curves',80,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdcol-none','pd-color-level','No requiere','none',10,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdcol-light','pd-color-level','Ajuste leve','light',20,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdcol-medium','pd-color-level','Ajuste medio','medium',30,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdcol-advanced','pd-color-level','Ajuste avanzado','advanced',40,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdca-correct','pd-color-actions','Corregir color','correct-color',10,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdca-recolor','pd-color-actions','Recolorear','recolor',20,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdca-mono','pd-color-actions','Pasar a monocromo','monochrome',30,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdca-white','pd-color-actions','Crear versión blanco','white-version',40,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdca-black','pd-color-actions','Crear versión negro','black-version',50,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdca-dark','pd-color-actions','Versión para fondo oscuro','dark-background',60,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdca-light','pd-color-actions','Versión para fondo claro','light-background',70,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdca-separate','pd-color-actions','Separar colores','separate-colors',80,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdca-reduce','pd-color-actions','Reducir colores','reduce-colors',90,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdca-contrast','pd-color-actions','Adaptar contraste para estampado','print-contrast',100,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdpo-dtf','pd-print-output','DTF','dtf',10,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdpo-sub','pd-print-output','Sublimación','sublimation',20,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdpa-size','pd-print-actions','Ajustar tamaño final','adjust-size',10,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdpa-res','pd-print-actions','Ajustar resolución','adjust-resolution',20,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdpa-alpha','pd-print-actions','Dejar fondo transparente','transparent-background',30,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdpa-edges','pd-print-actions','Limpiar bordes finales','clean-final-edges',40,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdpa-print','pd-print-actions','Preparar archivo final para impresión','final-print-file',50,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdpa-black','pd-print-actions','Adaptar para remera negra','black-shirt',60,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdpa-white','pd-print-actions','Adaptar para remera blanca','white-shirt',70,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdpa-color','pd-print-actions','Adaptar para color','color-shirt',80,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdpa-contrast','pd-print-actions','Revisar contraste','review-contrast',90,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdpa-mirror','pd-print-actions','Preparar versión espejada','mirror-version',100,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdpa-png','pd-print-actions','Preparar archivo PNG','png',110,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdpa-psd','pd-print-actions','Preparar archivo PSD','psd',120,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdpa-ai','pd-print-actions','Preparar archivo AI','ai',130,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdpa-svg','pd-print-actions','Preparar archivo SVG','svg',140,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdpa-many','pd-print-actions','Preparar varias salidas','multiple-outputs',150,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdun-cm','pd-unit','cm','cm',10,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdun-px','pd-unit','px','px',20,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdfm-png','pd-format','PNG','png',10,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdfm-psd','pd-format','PSD','psd',20,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdfm-ai','pd-format','AI','ai',30,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdfm-svg','pd-format','SVG','svg',40,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdfm-pdf','pd-format','PDF','pdf',50,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdfm-other','pd-format','Otro','other',60,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdhl-none','pd-halftone-level','No requiere','none',10,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdhl-simple','pd-halftone-level','Semitono simple','simple',20,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdhl-medium','pd-halftone-level','Semitono medio','medium',30,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdhl-advanced','pd-halftone-level','Semitono avanzado','advanced',40,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdhd-light','pd-halftone-details','Solo adaptación leve','light-adaptation',10,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdhd-full','pd-halftone-details','Conversión completa','full-conversion',20,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdhd-dark','pd-halftone-details','Ajuste para prenda oscura','dark-shirt',30,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdhd-light-shirt','pd-halftone-details','Ajuste para prenda clara','light-shirt',40,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdhd-test','pd-halftone-details','Requiere prueba visual','visual-test',50,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdhd-clean','pd-halftone-details','Requiere limpieza posterior','post-cleaning',60,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdres-none','pd-resource-level','No requiere','none',10,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdres-simple','pd-resource-level','Búsqueda simple','simple',20,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdres-medium','pd-resource-level','Búsqueda media','medium',30,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdres-wide','pd-resource-level','Búsqueda amplia','wide',40,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdrty-images','pd-resource-types','Imágenes','images',10,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdrty-textures','pd-resource-types','Texturas','textures',20,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdrty-fonts','pd-resource-types','Tipografías','fonts',30,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdrty-vectors','pd-resource-types','Vectores','vectors',40,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdrty-backgrounds','pd-resource-types','Fondos','backgrounds',50,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdrty-support','pd-resource-types','Recursos de apoyo','support',60,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdrty-refs','pd-resource-types','Referencias visuales','references',70,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdeb-1','pd-element-band','1 elemento','one',10,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdeb-2-3','pd-element-band','2 a 3 elementos','two-three',20,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdeb-4-6','pd-element-band','4 a 6 elementos','four-six',30,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdeb-7-10','pd-element-band','7 a 10 elementos','seven-ten',40,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdeb-more','pd-element-band','Más de 10 elementos','more-ten',50,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdpr-1','pd-proposals','1 propuesta','one',10,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdpr-2','pd-proposals','2 propuestas','two',20,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdpr-3','pd-proposals','3 propuestas','three',30,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdpr-4','pd-proposals','4 o más propuestas','four-plus',40,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdrv-0','pd-revisions','0','zero',10,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdrv-1','pd-revisions','1','one',20,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdrv-2','pd-revisions','2','two',30,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdrv-3','pd-revisions','3','three',40,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdrv-4','pd-revisions','4 o más','four-plus',50,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdvar-none','pd-variant-level','No requiere','none',10,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdvar-1','pd-variant-level','1 variante','one',20,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdvar-2','pd-variant-level','2 variantes','two',30,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdvar-3','pd-variant-level','3 variantes','three',40,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdvar-4','pd-variant-level','4 o más variantes','four-plus',50,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdvt-color','pd-variant-types','Cambio de color','color',10,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdvt-text','pd-variant-types','Cambio de texto','text',20,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdvt-bg','pd-variant-types','Cambio de fondo','background',30,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdvt-black','pd-variant-types','Versión para prenda negra','black-shirt',40,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdvt-white','pd-variant-types','Versión para prenda blanca','white-shirt',50,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdvt-color-shirt','pd-variant-types','Versión para color','color-shirt',60,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdvt-vertical','pd-variant-types','Versión vertical','vertical',70,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdvt-horizontal','pd-variant-types','Versión horizontal','horizontal',80,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdvt-sizes','pd-variant-types','Diferentes tamaños','sizes',90,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdloc-chest','pd-locations','Pecho','chest',10,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdloc-back','pd-locations','Espalda','back',20,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdloc-sleeve','pd-locations','Manga','sleeve',30,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdloc-full','pd-locations','Tamaño completo','full-size',40,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdloc-child','pd-locations','Infantil','child',50,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdloc-adult','pd-locations','Adulto','adult',60,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pded-no','pd-editable','No','none',10,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pded-psd','pd-editable','Sí, PSD','psd',20,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pded-ai','pd-editable','Sí, AI','ai',30,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pded-svg','pd-editable','Sí, SVG','svg',40,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pded-other','pd-editable','Sí, otro','other',50,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdur-normal','pd-urgency','Normal','normal',10,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdur-priority','pd-urgency','Prioritario','priority',20,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdur-urgent','pd-urgency','Urgente','urgent',30,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdur-very','pd-urgency','Muy urgente','very-urgent',40,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdor-ready','pd-origin','El cliente trae diseño listo','ready',10,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdor-base','pd-origin','El cliente trae base para corregir','base-to-correct',20,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdor-reference','pd-origin','El cliente trae referencia y hay que rehacer','reference-to-redo',30,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('pdor-scratch','pd-origin','Hay que diseñar desde cero','from-scratch',40,1,strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now'));

-- Fuentes seguras: BCRA sólo convierte moneda. Las referencias genéricas de
-- diseño quedan como contexto/manual y no pueden sugerir importes por sí solas.
INSERT OR IGNORE INTO pricing_engine_sources (
  engine_id,source_id,role,preference,participates_in_suggestions,match_score_micros,
  explanation,assigned_by,created_at,updated_at
) VALUES
('engine-print-design','source-bcra','cost_input','preferred',0,1000000,'Conversión USD/ARS; no aporta tarifas profesionales.','automatic',strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('engine-print-design','source-tarifario','context','available',0,700000,'Referencia manual de diseño; requiere evidencia específica de estampas.','automatic',strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('engine-print-design','source-adg','context','available',0,700000,'Contexto profesional de diseño; no participa sin datos comparables verificados.','automatic',strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('engine-print-design','source-workana','context','available',0,600000,'Marketplace manual; no se reutilizan tarifas de otras profesiones.','automatic',strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('engine-print-design','source-upwork','context','available',0,600000,'Marketplace bloqueado para automatización; sólo contexto verificado.','automatic',strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('engine-print-design','source-fiverr','context','available',0,600000,'Marketplace manual; no participa automáticamente.','automatic',strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')),
('engine-print-design','source-twine','context','available',0,600000,'Marketplace creativo manual; no participa automáticamente.','automatic',strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now'));

INSERT OR IGNORE INTO classification_aliases (
  id,normalized_term,engine_type,category_id,tags_json,origin,created_at,updated_at
) VALUES (
  'alias-diseno-estampas','diseno de estampas','service','category-design',
  '["diseño gráfico","estampas","dtf","sublimación"]','system',
  strftime('%Y-%m-%dT%H:%M:%fZ','now'),strftime('%Y-%m-%dT%H:%M:%fZ','now')
);
