import { PackagePlus, Plus, Trash2 } from "lucide-react";
import type { Currency, ServiceResult } from "../../domain/types";
import type { HybridConfiguration, ProductConfiguration, ProductCost } from "../../domain/product";
import { majorToMinor, minorToInput, formatMoney } from "../../domain/money";
import { Button, Field, Input, Select } from "../../components/ui";

export function ProductEditor({ config, currency, hybrid, result, onChange }: { config: ProductConfiguration | HybridConfiguration; currency: Currency; hybrid: boolean; result: ServiceResult | undefined; onChange: (config: ProductConfiguration | HybridConfiguration, immediate?: boolean) => void }) {
  const update = (next: Partial<ProductConfiguration | HybridConfiguration>, immediate = false) => onChange({ ...config, ...next }, immediate);
  const addCost = () => update({ costs: [...config.costs, { id: crypto.randomUUID(), name: "", amountMinor: 0, currency, scope: "per_unit", category: "material" }] }, true);
  const updateCost = (id: string, next: Partial<ProductCost>) => update({ costs: config.costs.map((cost) => cost.id === id ? { ...cost, ...next } : cost) });
  const removeCost = (id: string) => update({ costs: config.costs.filter((cost) => cost.id !== id) }, true);
  return <div className="product-editor">
    <section className="editor-section"><div className="editor-section__heading"><div><span className="eyebrow">Producción</span><h3>Qué vas a vender</h3><p>La cantidad transforma costos unitarios en el costo total del lote.</p></div><PackagePlus size={22} /></div><div className="form-grid"><Field label="Cantidad" hint="Unidades que producirás o venderás en este cálculo."><Input type="number" min="1" step="1" value={config.quantity} onChange={(event) => update({ quantity: Number(event.target.value) })} /></Field>{hybrid && <><Field label="Horas del servicio" hint="Trabajo profesional incluido además del producto físico."><Input type="number" min="0" step="0.25" value={(config as HybridConfiguration).serviceHours ?? ""} onChange={(event) => update({ serviceHours: event.target.value ? Number(event.target.value) : null })} /></Field><Field label="Nombre del trabajo profesional" hint="Aparece como una línea separada en el desglose del motor híbrido." className="span-2"><Input value={(config as HybridConfiguration).serviceLabel} onChange={(event) => update({ serviceLabel: event.target.value })} /></Field></>}</div></section>
    <section className="editor-section"><div className="config-toolbar"><div><span className="eyebrow">Costo real</span><h3>Costos de producto</h3><p>Indicá si el importe corresponde a cada unidad o al lote completo.</p></div><Button onClick={addCost}><Plus size={16} /> Agregar costo</Button></div><div className="product-cost-list">{config.costs.map((cost) => <div className="product-cost-row" key={cost.id}><Field label="Concepto" hint="Ej.: remera base, estampado, packaging."><Input placeholder="Nombre del costo" value={cost.name} onChange={(event) => updateCost(cost.id, { name: event.target.value })} /></Field><Field label="Importe" hint="Costo en la moneda original; el cambio se aplica sin perder ese valor."><Input type="number" min="0" step="0.01" value={minorToInput(cost.amountMinor)} onChange={(event) => updateCost(cost.id, { amountMinor: majorToMinor(event.target.value) ?? 0 })} /></Field><Field label="Moneda" hint="Moneda en la que pagás realmente este costo."><Select value={cost.currency} onChange={(event) => updateCost(cost.id, { currency: event.target.value as Currency })}><option value="ARS">ARS</option><option value="USD">USD</option></Select></Field><Field label="Aplicación" hint="Por unidad se multiplica por cantidad; por lote se suma una sola vez."><Select value={cost.scope} onChange={(event) => updateCost(cost.id, { scope: event.target.value as ProductCost["scope"] })}><option value="per_unit">Por unidad</option><option value="batch">Por lote</option></Select></Field><Field label="Categoría" hint="Ordena el desglose; no cambia la fórmula por sí sola."><Select value={cost.category} onChange={(event) => updateCost(cost.id, { category: event.target.value as ProductCost["category"] })}><option value="material">Material / mercadería</option><option value="production">Producción</option><option value="packaging">Packaging</option><option value="operations">Operación</option><option value="logistics">Logística</option><option value="other">Otro</option></Select></Field><button className="product-cost-remove" title="Quitar costo" aria-label={`Quitar ${cost.name || "costo"}`} onClick={() => removeCost(cost.id)}><Trash2 size={16} /></button></div>)}{config.costs.length === 0 && <button className="product-cost-empty" onClick={addCost}><Plus size={18} /><strong>Agregá el primer costo</strong><span>Puede ser unitario o correspondiente al lote completo.</span></button>}</div></section>
    <section className="editor-section"><span className="eyebrow">Venta y sostenibilidad</span><h3>Porcentajes sobre el producto</h3><div className="form-grid product-percent-grid"><Field label="Merma · %" hint="Cubre desperdicio, fallas o unidades que no llegan a venderse."><Input type="number" min="0" max="99.99" step="0.1" value={config.wastePercent} onChange={(event) => update({ wastePercent: Number(event.target.value) })} /></Field><Field label="Comisiones · %" hint="Porcentaje que retiene una plataforma o medio de cobro sobre la venta."><Input type="number" min="0" max="99.99" step="0.1" value={config.commissionPercent} onChange={(event) => update({ commissionPercent: Number(event.target.value) })} /></Field><Field label="Impuestos · %" hint="Reserva configurable aplicada sobre el precio de venta."><Input type="number" min="0" max="99.99" step="0.1" value={config.taxPercent} onChange={(event) => update({ taxPercent: Number(event.target.value) })} /></Field><Field label="Margen recomendado · %" hint="Beneficio objetivo después de costos, comisiones e impuestos."><Input type="number" min="0" max="99.99" step="0.1" value={config.recommendedMarginPercent} onChange={(event) => update({ recommendedMarginPercent: Number(event.target.value) })} /></Field><Field label="Margen premium · %" hint="Posicionamiento superior. Debe ser igual o mayor al recomendado."><Input type="number" min="0" max="99.99" step="0.1" value={config.premiumMarginPercent} onChange={(event) => update({ premiumMarginPercent: Number(event.target.value) })} /></Field></div></section>
    <section className="editor-section"><span className="eyebrow">Precio elegido</span><h3>Piso, recomendado o premium</h3><p>El piso evita pérdidas; el recomendado y el premium aplican tus márgenes configurados.</p><div className="product-tier-selector">{(["floor", "recommended", "premium"] as const).map((tier) => <button key={tier} className={config.selectedTier === tier ? "is-active" : ""} disabled={!result?.pricingTiers} onClick={() => update({ selectedTier: tier }, true)}><span>{tier === "floor" ? "Piso" : tier === "recommended" ? "Recomendado" : "Premium"}</span><strong>{formatMoney(result?.pricingTiers?.[tier].unitMinor, currency)}</strong><small>por unidad · {formatMoney(result?.pricingTiers?.[tier].totalMinor, currency)} total</small></button>)}</div></section>
  </div>;
}
