import { invoke } from "@tauri-apps/api/core";
import type {
  AppSettings,
  Bootstrap,
  Client,
  ClientInput,
  CreateProjectInput,
  Preset,
  PresetInput,
  QuoteService,
  SaveServiceInput,
  SettingsInput,
  Workspace,
  PricingConfiguration,
  ServiceDefinitionInput,
  ServiceParameterInput,
  ParameterOptionInput,
  PricingRuleInput,
  EconomicProfileInput,
  MarketSourceInput,
  ManualObservationInput,
  MarketObservation,
  MarketObservationFilter,
  MarketOverview,
  MarketResearchJob,
  MarketSnapshot,
  SourceTestResult,
  ClassificationInput,
  ClassificationProposal,
  SourceClassificationInput,
  SourceClassificationProposal,
  PricingEngine,
  PricingEngineInput,
  EngineSourceInput,
  PricingEngineSource,
  OllamaStatus,
  QuoteHistoryItem,
  QuoteHistoryDetail,
  SaveQuoteSnapshotInput,
  UpdateQuoteAdminInput,
  DuplicateQuoteInput,
  ProfessionalProfile,
  ProfessionalProfileInput,
  ClientDocumentConfig,
  ClientQuoteDocument,
  ExportedFile,
  BackupSummary,
  RestoreResult,
} from "../domain/types";

export const api = {
  bootstrap: () => invoke<Bootstrap>("bootstrap_app"),
  loadWorkspace: (projectId: string) => invoke<Workspace>("load_workspace", { projectId }),
  createProject: (input: CreateProjectInput) => invoke<Workspace>("create_project", { input }),
  saveClient: (input: ClientInput) => invoke<Client>("save_client", { input }),
  setClientArchived: (id: string, archived: boolean) => invoke<void>("set_client_archived", { id, archived }),
  setProjectArchived: (id: string, archived: boolean) => invoke<void>("set_project_archived", { id, archived }),
  addService: (quoteId: string, serviceType: string) =>
    invoke<QuoteService>("add_quote_service", { quoteId, serviceType }),
  saveService: (input: SaveServiceInput) => invoke<QuoteService>("save_quote_service", { input }),
  setServiceDeleted: (id: string, deleted: boolean) => invoke<void>("set_service_deleted", { id, deleted }),
  reorderServices: (quoteId: string, orderedIds: string[]) => invoke<void>("reorder_quote_services", { quoteId, orderedIds }),
  updateSettings: (input: SettingsInput) => invoke<AppSettings>("update_settings", { input }),
  changeCurrency: (projectId: string, currency: "ARS" | "USD") =>
    invoke<Workspace>("change_project_currency", { projectId, currency }),
  savePreset: (input: PresetInput) => invoke<Preset>("save_preset", { input }),
  deleteUserPreset: (id: string) => invoke<void>("delete_user_preset", { id }),
  restoreSystemPreset: (id: string) => invoke<Preset>("restore_system_preset", { id }),
  loadPricing: () => invoke<PricingConfiguration>("load_pricing_configuration"),
  saveServiceDefinition: (input: ServiceDefinitionInput) => invoke<PricingConfiguration>("save_service_definition", { input }),
  saveServiceParameter: (input: ServiceParameterInput) => invoke<PricingConfiguration>("save_service_parameter", { input }),
  deleteServiceParameter: (id: string) => invoke<PricingConfiguration>("delete_service_parameter", { id }),
  saveParameterOption: (input: ParameterOptionInput) => invoke<PricingConfiguration>("save_parameter_option", { input }),
  deleteParameterOption: (id: string) => invoke<PricingConfiguration>("delete_parameter_option", { id }),
  savePricingRule: (input: PricingRuleInput) => invoke<PricingConfiguration>("save_pricing_rule", { input }),
  deletePricingRule: (id: string) => invoke<PricingConfiguration>("delete_pricing_rule", { id }),
  saveEconomicProfile: (input: EconomicProfileInput) => invoke<PricingConfiguration>("save_economic_profile", { input }),
  extractEconomyPdfText: (dataUrl: string) => invoke<string>("extract_economy_pdf_text", { dataUrl }),
  saveMarketSource: (input: MarketSourceInput) => invoke<PricingConfiguration>("save_market_source", { input }),
  deleteMarketSource: (id: string) => invoke<PricingConfiguration>("delete_market_source", { id }),
  restoreMarketSource: (id: string) => invoke<PricingConfiguration>("restore_market_source", { id }),
  restoreMarketSourcesCatalog: () => invoke<PricingConfiguration>("restore_market_sources_catalog"),
  testMarketSource: (id: string) => invoke<SourceTestResult>("test_market_source", { id }),
  approveMarketSource: (id: string) => invoke<PricingConfiguration>("approve_market_source", { id }),
  refreshMarketSource: (id: string, force = false) => invoke<SourceTestResult>("refresh_market_source", { id, force }),
  saveManualMarketObservation: (input: ManualObservationInput) => invoke<MarketObservation>("save_manual_market_observation", { input }),
  listMarketObservations: (filter: MarketObservationFilter = {}) => invoke<MarketObservation[]>("list_market_observations", { filter }),
  listMarketSnapshots: (quoteServiceId?: string) => invoke<MarketSnapshot[]>("list_market_snapshots", { quoteServiceId }),
  getMarketOverview: (quoteServiceId: string) => invoke<MarketOverview>("get_market_overview", { quoteServiceId }),
  startMarketResearch: (quoteServiceId: string, force = false) => invoke<MarketResearchJob>("start_market_research", { quoteServiceId, force }),
  getMarketResearchJob: (id: string) => invoke<MarketResearchJob>("get_market_research_job", { id }),
  cancelMarketResearch: (id: string) => invoke<MarketResearchJob>("cancel_market_research", { id }),
  openMarketSource: (url: string) => invoke<void>("open_market_source", { url }),
  classifyPricingEngine: (input: ClassificationInput) => invoke<ClassificationProposal>("classify_pricing_engine", { input }),
  classifyMarketSource: (input: SourceClassificationInput) => invoke<SourceClassificationProposal>("classify_market_source", { input }),
  testOllama: () => invoke<OllamaStatus>("test_ollama"),
  savePricingEngine: (input: PricingEngineInput) => invoke<PricingEngine>("save_pricing_engine", { input }),
  setPricingEngineArchived: (id: string, archived: boolean) => invoke<PricingEngine>("set_pricing_engine_archived", { id, archived }),
  saveEngineSource: (input: EngineSourceInput) => invoke<PricingEngineSource>("save_engine_source", { input }),
  removeEngineSource: (engineId: string, sourceId: string) => invoke<void>("remove_engine_source", { engineId, sourceId }),
  listQuoteHistory: () => invoke<QuoteHistoryItem[]>("list_quote_history"),
  getQuoteHistory: (quoteId: string, revision?: number) => invoke<QuoteHistoryDetail>("get_quote_history", { quoteId, revision }),
  saveQuoteSnapshot: (input: SaveQuoteSnapshotInput) => invoke<QuoteHistoryDetail>("save_quote_snapshot", { input }),
  updateQuoteAdmin: (input: UpdateQuoteAdminInput) => invoke<QuoteHistoryItem>("update_quote_admin", { input }),
  duplicateQuote: (input: DuplicateQuoteInput) => invoke<Workspace>("duplicate_quote", { input }),
  deleteQuotePermanently: (quoteId: string) => invoke<void>("delete_quote_permanently", { quoteId }),
  getProfessionalProfile: () => invoke<ProfessionalProfile>("get_professional_profile"),
  saveProfessionalProfile: (input: ProfessionalProfileInput) => invoke<ProfessionalProfile>("save_professional_profile", { input }),
  getClientDocumentConfig: (quoteId: string) => invoke<ClientDocumentConfig>("get_client_document_config", { quoteId }),
  saveClientDocumentConfig: (config: ClientDocumentConfig) => invoke<void>("save_client_document_config", { config }),
  createClientQuoteDocument: (config: ClientDocumentConfig) => invoke<ClientQuoteDocument>("create_client_quote_document", { config }),
  exportClientQuotePdf: (document: ClientQuoteDocument) => invoke<ExportedFile>("export_client_quote_pdf", { document }),
  createPricingBackup: () => invoke<ExportedFile>("create_pricing_backup"),
  inspectPricingBackup: (content: string) => invoke<BackupSummary>("inspect_pricing_backup", { content }),
  restorePricingBackup: (content: string) => invoke<RestoreResult>("restore_pricing_backup", { content }),
};
