import { invoke } from "@tauri-apps/api/core";
import type {
  AppSettings,
  Bootstrap,
  Client,
  ClientInput,
  CreateProjectInput,
  Preset,
  PresetInput,
  QuoteService,
  SaveServiceInput,
  SettingsInput,
  Workspace,
  PricingConfiguration,
  ServiceDefinitionInput,
  ServiceParameterInput,
  ParameterOptionInput,
  PricingRuleInput,
  EconomicProfileInput,
  MarketSourceInput,
} from "../domain/types";

export const api = {
  bootstrap: () => invoke<Bootstrap>("bootstrap_app"),
  loadWorkspace: (projectId: string) => invoke<Workspace>("load_workspace", { projectId }),
  createProject: (input: CreateProjectInput) => invoke<Workspace>("create_project", { input }),
  saveClient: (input: ClientInput) => invoke<Client>("save_client", { input }),
  setClientArchived: (id: string, archived: boolean) => invoke<void>("set_client_archived", { id, archived }),
  setProjectArchived: (id: string, archived: boolean) => invoke<void>("set_project_archived", { id, archived }),
  addService: (quoteId: string, serviceType: "video-editing" | "programming") =>
    invoke<QuoteService>("add_quote_service", { quoteId, serviceType }),
  saveService: (input: SaveServiceInput) => invoke<QuoteService>("save_quote_service", { input }),
  setServiceDeleted: (id: string, deleted: boolean) => invoke<void>("set_service_deleted", { id, deleted }),
  reorderServices: (quoteId: string, orderedIds: string[]) => invoke<void>("reorder_quote_services", { quoteId, orderedIds }),
  updateSettings: (input: SettingsInput) => invoke<AppSettings>("update_settings", { input }),
  changeCurrency: (projectId: string, currency: "ARS" | "USD") =>
    invoke<Workspace>("change_project_currency", { projectId, currency }),
  savePreset: (input: PresetInput) => invoke<Preset>("save_preset", { input }),
  deleteUserPreset: (id: string) => invoke<void>("delete_user_preset", { id }),
  restoreSystemPreset: (id: string) => invoke<Preset>("restore_system_preset", { id }),
  loadPricing: () => invoke<PricingConfiguration>("load_pricing_configuration"),
  saveServiceDefinition: (input: ServiceDefinitionInput) => invoke<PricingConfiguration>("save_service_definition", { input }),
  saveServiceParameter: (input: ServiceParameterInput) => invoke<PricingConfiguration>("save_service_parameter", { input }),
  deleteServiceParameter: (id: string) => invoke<PricingConfiguration>("delete_service_parameter", { id }),
  saveParameterOption: (input: ParameterOptionInput) => invoke<PricingConfiguration>("save_parameter_option", { input }),
  deleteParameterOption: (id: string) => invoke<PricingConfiguration>("delete_parameter_option", { id }),
  savePricingRule: (input: PricingRuleInput) => invoke<PricingConfiguration>("save_pricing_rule", { input }),
  deletePricingRule: (id: string) => invoke<PricingConfiguration>("delete_pricing_rule", { id }),
  saveEconomicProfile: (input: EconomicProfileInput) => invoke<PricingConfiguration>("save_economic_profile", { input }),
  saveMarketSource: (input: MarketSourceInput) => invoke<PricingConfiguration>("save_market_source", { input }),
  deleteMarketSource: (id: string) => invoke<PricingConfiguration>("delete_market_source", { id }),
  restoreMarketSource: (id: string) => invoke<PricingConfiguration>("restore_market_source", { id }),
};
