import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, Database, Filter, RefreshCw, Settings2, XCircle } from "lucide-react";
import type { MarketObservation, MarketResearchJob, MarketSnapshot, PricingConfiguration } from "../../domain/types";
import { api } from "../../services/api";
import { Button, Select } from "../../components/ui";

export function MarketView({ pricing, activeServiceId, job, onResearch, onCancel, onConfigureSources }: { pricing: PricingConfiguration; activeServiceId: string | null; job: MarketResearchJob | null; onResearch: (force?: boolean) => Promise<void>; onCancel: () => Promise<void>; onConfigureSources: () => void }) {
  const [observations, setObservations] = useState<MarketObservation[]>([]);
  const [snapshots, setSnapshots] = useState<MarketSnapshot[]>([]);
  const [loading, setLoading] = useState(true);
  const [loadError, setLoadError] = useState("");
  const [retryKey, setRetryKey] = useState(0);
  const [loadedAt, setLoadedAt] = useState(0);
  const [filters, setFilters] = useState({ service: "all", subservice: "all", region: "all", source: "all", type: "all", currency: "all", date: "all" });

  useEffect(() => { let cancelled = false; Promise.all([api.listMarketObservations(), api.listMarketSnapshots()]).then(([nextObservations, nextSnapshots]) => { if (!cancelled) { setObservations(nextObservations); setSnapshots(nextSnapshots); setLoadedAt(Date.now()); setLoadError(""); } }).catch((error) => { if (!cancelled) setLoadError(`No se pudo cargar el historial local. ${String(error)}`); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, [job?.status, retryKey]);
  const rows = useMemo(() => observations.filter((row) => {
    const ageDays = (loadedAt - new Date(row.publishedAt || row.retrievedAt).getTime()) / 86_400_000;
    return (filters.service === "all" || row.serviceType === filters.service)
      && (filters.subservice === "all" || row.subservice === filters.subservice)
      && (filters.region === "all" || row.region === filters.region)
      && (filters.source === "all" || row.sourceId === filters.source)
      && (filters.type === "all" || row.priceType === filters.type)
      && (filters.currency === "all" || row.currency === filters.currency)
      && (filters.date === "all" || ageDays <= Number(filters.date));
  }), [filters, loadedAt, observations]);
  const unique = (selector: (row: MarketObservation) => string) => [...new Set(observations.map(selector).filter(Boolean))].sort();
  const running = job?.status === "RUNNING";

  return <div className="view-page market-view"><header className="page-header market-view__header"><div><span className="eyebrow">Market Intelligence</span><h1>Mercado</h1><p>Observaciones trazables y snapshots históricos. Cada precio conserva fuente, unidad, moneda y fecha.</p></div><div className="market-view__actions"><Button onClick={onConfigureSources}><Settings2 size={16} /> Configurar fuentes</Button>{running ? <Button variant="danger" onClick={onCancel}><XCircle size={16} /> Cancelar</Button> : <Button variant="accent" disabled={!activeServiceId} onClick={() => onResearch(false)}><RefreshCw size={16} /> Actualizar servicio activo</Button>}</div></header>
    {running && <ResearchProgress job={job} onCancel={onCancel} />}
    {!activeServiceId && <div className="inline-notice" role="status">Abrí una cotización y elegí un servicio para crear una investigación contextual.</div>}
    {loadError && <div className="inline-notice inline-notice--error" role="alert"><span>{loadError}</span><Button onClick={() => { setLoading(true); setLoadError(""); setRetryKey((value) => value + 1); }}>Reintentar</Button></div>}
    <section className="market-section"><div className="market-section__heading"><div><span className="eyebrow">Observaciones</span><h2>Evidencia obtenida</h2></div><span>{rows.length} de {observations.length}</span></div><div className="market-filters"><Filter size={16} aria-hidden="true" /><Select aria-label="Servicio" value={filters.service} onChange={(event) => setFilters({ ...filters, service: event.target.value })}><option value="all">Todos los servicios</option><option value="video-editing">Video</option><option value="programming">Programación</option></Select><Select aria-label="Subservicio" value={filters.subservice} onChange={(event) => setFilters({ ...filters, subservice: event.target.value })}><option value="all">Todos los subservicios</option>{unique((row) => row.subservice || "").map((value) => <option key={value}>{value}</option>)}</Select><Select aria-label="Región" value={filters.region} onChange={(event) => setFilters({ ...filters, region: event.target.value })}><option value="all">Todas las regiones</option>{unique((row) => row.region).map((value) => <option key={value}>{value}</option>)}</Select><Select aria-label="Fuente" value={filters.source} onChange={(event) => setFilters({ ...filters, source: event.target.value })}><option value="all">Todas las fuentes</option>{pricing.marketSources.map((source) => <option key={source.id} value={source.id}>{source.name}</option>)}</Select><Select aria-label="Tipo" value={filters.type} onChange={(event) => setFilters({ ...filters, type: event.target.value })}><option value="all">Todos los tipos</option>{unique((row) => row.priceType).map((value) => <option key={value}>{value}</option>)}</Select><Select aria-label="Moneda" value={filters.currency} onChange={(event) => setFilters({ ...filters, currency: event.target.value })}><option value="all">Todas las monedas</option>{unique((row) => row.currency).map((value) => <option key={value}>{value}</option>)}</Select><Select aria-label="Fecha" value={filters.date} onChange={(event) => setFilters({ ...filters, date: event.target.value })}><option value="all">Todas las fechas</option><option value="30">Últimos 30 días</option><option value="90">Últimos 90 días</option><option value="365">Último año</option></Select></div>
      {loading ? <p className="market-loading" role="status">Cargando inteligencia local…</p> : rows.length === 0 ? <div className="market-empty"><Database size={28} aria-hidden="true" /><strong>Todavía no hay datos para estos filtros</strong><span>Podés actualizar una fuente aprobada o cargar una observación manual.</span></div> : <div className="market-data-table" role="table" aria-label="Observaciones de mercado" tabIndex={0}><div className="market-data-row market-data-row--head" role="row"><span role="columnheader">Fuente / servicio</span><span role="columnheader">Precio original</span><span role="columnheader">Unidad</span><span role="columnheader">Región</span><span role="columnheader">Fecha</span><span role="columnheader">Uso</span><span role="columnheader" /></div>{rows.map((row) => <div className="market-data-row" role="row" key={row.id}><span role="cell"><strong>{row.sourceName}</strong><small>{row.subservice || row.serviceType}</small></span><span role="cell">{marketPrice(row)}</span><span role="cell">{row.priceType.replaceAll("_", " ")}<small>{row.unit}</small></span><span role="cell">{row.region}</span><span role="cell">{new Date(row.publishedAt || row.retrievedAt).toLocaleDateString("es-AR")}</span><span role="cell"><b className={row.comparisonEligibility === "ELIGIBLE" ? "comparison-yes" : "comparison-no"}>{row.comparisonEligibility === "ELIGIBLE" ? "Comparable" : "Contexto"}</b><small>{row.exclusionReason}</small></span><button type="button" aria-label={`Abrir ${row.sourceName}`} onClick={() => api.openMarketSource(row.sourceUrl)}><ArrowUpRight size={15} aria-hidden="true" /></button></div>)}</div>}
    </section>
    <section className="market-section"><div className="market-section__heading"><div><span className="eyebrow">Historial inmutable</span><h2>Snapshots</h2></div><span>{snapshots.length}</span></div>{snapshots.length === 0 ? <div className="market-empty"><span>La primera actualización contextual creará un snapshot fechado.</span></div> : <div className="snapshot-list">{snapshots.map((snapshot) => <article key={snapshot.id}><time>{new Date(snapshot.createdAt).toLocaleString("es-AR")}</time><strong>{snapshot.currency} {snapshot.marketMedianMinor == null ? "Sin mediana" : (snapshot.marketMedianMinor / 100).toLocaleString("es-AR")}</strong><span>{snapshot.comparableObservationCount} comparables · {snapshot.sourceCount} fuentes · confianza {snapshot.confidenceLevel.toLocaleLowerCase("es-AR")}</span><small>{snapshot.minimumFilteredMinor == null ? "Mercado insuficiente" : `Rango filtrado ${(snapshot.minimumFilteredMinor / 100).toLocaleString("es-AR")}–${((snapshot.maximumFilteredMinor ?? 0) / 100).toLocaleString("es-AR")}`}</small></article>)}</div>}</section>
  </div>;
}

export function ResearchProgress({ job, onCancel }: { job: MarketResearchJob; onCancel: () => Promise<void> }) { return <section className="research-progress" aria-live="polite"><header><div><span className="eyebrow">Actualizando mercado</span><strong>{job.completed} / {job.total} fuentes procesadas</strong></div><Button variant="danger" onClick={onCancel}>Cancelar</Button></header><div>{job.items.map((item) => <p key={item.sourceId}><span>{item.sourceName}</span><b className={`research-state research-state--${item.status.toLowerCase()}`}>{item.status.replaceAll("_", " ")}</b><small>{item.message}</small></p>)}</div></section>; }

function marketPrice(row: MarketObservation) { if (row.priceValueMinor != null) return `${row.currency} ${(row.priceValueMinor / 100).toLocaleString("es-AR", { maximumFractionDigits: 2 })}`; return `${row.currency} ${row.priceMinMinor == null ? "—" : (row.priceMinMinor / 100).toLocaleString("es-AR")}–${row.priceMaxMinor == null ? "—" : (row.priceMaxMinor / 100).toLocaleString("es-AR")}`; }
