import { Plus, Trash2 } from "lucide-react";
import type { Currency, PricingConfiguration, QuoteService } from "../../domain/types";
import type { ProgrammingConfiguration } from "../../domain/programming";
import { emptyExternalCost } from "../../domain/programming";
import { majorToMinor, minorToInput } from "../../domain/money";
import { DynamicFields } from "../../components/DynamicFields";
import { Button, Field, Input, Select } from "../../components/ui";

export function ProgrammingEditor({ service, config, currency, pricing, suggestionsEnabled, onChange }: { service: QuoteService; config: ProgrammingConfiguration; currency: Currency; pricing: PricingConfiguration; suggestionsEnabled: boolean; onChange: (config: ProgrammingConfiguration) => void }) {
  const definition = pricing.definitions.find((item) => item.serviceType === service.serviceType);
  const parameters = pricing.parameters.filter((item) => item.serviceDefinitionId === definition?.id && !item.uiManaged);
  const updateCost = (index: number, patch: Partial<ProgrammingConfiguration["externalCosts"][number]>) => onChange({ ...config, externalCosts: config.externalCosts.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item) });
  return <div className="dynamic-editor"><section className="editor-section"><span className="eyebrow">Programación configurable · definición v{definition?.version ?? 1}</span><h2>Alcance del producto</h2><p className="muted-line">Cada campo y regla se administra desde Configuración › Servicios. No hay coeficientes ocultos.</p><DynamicFields parameters={parameters} options={pricing.options} values={config.parameterValues} suggestionsEnabled={suggestionsEnabled} onChange={(parameterValues) => onChange({ ...config, parameterValues })} /></section><section className="editor-section"><Field label="Notas de alcance"><textarea className="input textarea" rows={4} value={config.notes} onChange={(e) => onChange({ ...config, notes: e.target.value })} /></Field></section><section className="editor-section"><div className="costs__header"><div><span className="eyebrow">Costos externos</span><h3>Licencias, infraestructura y terceros</h3></div><Button type="button" onClick={() => onChange({ ...config, externalCosts: [...config.externalCosts, emptyExternalCost(currency)] })}><Plus size={15} /> Agregar</Button></div>{config.externalCosts.map((cost, index) => <div className="cost-row" key={cost.id}><Input aria-label="Nombre del costo" placeholder="Nombre" value={cost.name} onChange={(e) => updateCost(index, { name: e.target.value })} /><Input aria-label="Importe" type="number" min="0" step="0.01" value={minorToInput(cost.amountMinor)} onChange={(e) => updateCost(index, { amountMinor: majorToMinor(e.target.value) ?? 0 })} /><Select aria-label="Moneda" value={cost.currency} onChange={(e) => updateCost(index, { currency: e.target.value as Currency })}><option>USD</option><option>ARS</option></Select><Input aria-label="Nota del costo" placeholder="Nota" value={cost.note} onChange={(e) => updateCost(index, { note: e.target.value })} /><button className="icon-button" onClick={() => onChange({ ...config, externalCosts: config.externalCosts.filter((_, itemIndex) => itemIndex !== index) })}><Trash2 size={16} /></button></div>)}</section></div>;
}
