import { useMemo, useState } from "react";
import { Archive, Bot, Boxes, Check, ChevronRight, Link2, Pencil, Plus, RotateCcw, Sparkles } from "lucide-react";
import type { ClassificationInput, ClassificationProposal, PricingConfiguration, PricingEngine, PricingEngineInput } from "../../domain/types";
import { api } from "../../services/api";
import { Button, Field, Input, Modal, Select } from "../../components/ui";

const typeLabel = { service: "Servicio", product: "Producto", hybrid: "Híbrido" } as const;
const calculatorLabel = { "professional-service-v1": "Servicio profesional", "physical-product-v1": "Producto físico", "hybrid-v1": "Servicio + producto", unconfigured: "Sin calculadora" } as const;

export function EngineManager({ pricing, onPricingChange }: { pricing: PricingConfiguration; onPricingChange: (pricing: PricingConfiguration) => void }) {
  const [selectedId, setSelectedId] = useState(pricing.pricingEngines.find((engine) => engine.status !== "archived")?.id ?? "");
  const [wizard, setWizard] = useState<PricingEngine | "new" | null>(null);
  const [notice, setNotice] = useState("");
  const selected = pricing.pricingEngines.find((engine) => engine.id === selectedId) ?? pricing.pricingEngines[0] ?? null;
  const assignments = useMemo(() => pricing.engineSources.filter((item) => item.engineId === selected?.id), [pricing.engineSources, selected?.id]);

  async function refresh(message?: string) {
    onPricingChange(await api.loadPricing());
    if (message) setNotice(message);
  }

  return <div className="engine-manager">
    <aside className="engine-manager__list">
      <div className="engine-manager__list-head"><div><span className="eyebrow">Motores de pricing</span><strong>{pricing.pricingEngines.filter((item) => item.status !== "archived").length} activos</strong></div><button aria-label="Crear motor" onClick={() => setWizard("new")}><Plus size={17} /></button></div>
      {pricing.pricingEngines.filter((engine) => engine.status !== "archived").map((engine) => <button key={engine.id} className={selected?.id === engine.id ? "is-active" : ""} onClick={() => setSelectedId(engine.id)}><span className={`engine-type-dot engine-type-dot--${engine.engineType}`} /><span><strong>{engine.name}</strong><small>{typeLabel[engine.engineType]} · {engine.status === "draft" ? "borrador" : "activo"}</small></span><ChevronRight size={15} /></button>)}
      <Button variant="accent" onClick={() => setWizard("new")}><Plus size={16} /> Nuevo motor</Button>
    </aside>
    <section className="engine-manager__content">
      {notice && <div className="inline-notice" role="status">{notice}</div>}
      {!selected ? <div className="engine-empty"><Boxes size={28} /><strong>Creá el primer motor</strong><p>Contanos qué querés calcular y Pricing OS preparará una clasificación revisable.</p></div> : <>
        <header className="engine-detail__header"><div><span className="eyebrow">{selected.isSystem ? "Motor del sistema" : "Motor personal"}</span><h2>{selected.name}</h2><p>{selected.description || "Sin descripción."}</p></div><div><span className={`engine-kind engine-kind--${selected.engineType}`}>{typeLabel[selected.engineType]}</span><Button onClick={() => setWizard(selected)}><Pencil size={15} /> Editar</Button>{!selected.isSystem && <Button variant="danger" onClick={async () => { if (window.confirm(`¿Archivar “${selected.name}”? Sus cotizaciones y fuentes se conservarán.`)) { await api.setPricingEngineArchived(selected.id, true); await refresh("Motor archivado sin perder datos."); } }}><Archive size={15} /> Archivar</Button>}</div></header>
        <div className="engine-facts"><div><span>Calculadora</span><strong>{calculatorLabel[selected.calculatorKey]}</strong></div><div><span>Unidad principal</span><strong>{selected.unitKind}</strong></div><div><span>Clasificación</span><strong>{selected.classificationOrigin === "ai_assisted" ? "IA local + reglas" : selected.classificationOrigin === "manual" ? "Corregida manualmente" : "Automática"}</strong></div><div><span>Confianza</span><strong>{selected.classificationConfidenceMicros == null ? "—" : `${Math.round(selected.classificationConfidenceMicros / 10_000)}%`}</strong></div></div>
        <section className="engine-classification"><span className="eyebrow">Qué entendió Pricing OS</span><p>{selected.classificationExplanation || "Clasificación confirmada por el usuario."}</p><div className="tag-list">{parseTags(selected.tagsJson).map((tag) => <span key={tag}>{tag}</span>)}</div></section>
        <EngineSources engine={selected} pricing={pricing} assignments={assignments} onRefresh={refresh} />
      </>}
    </section>
    {wizard && <EngineWizard engine={wizard === "new" ? null : wizard} pricing={pricing} onClose={() => setWizard(null)} onSaved={async (engine) => { setWizard(null); setSelectedId(engine.id); await refresh(engine.classificationOrigin === "ai_assisted" ? "Motor creado con clasificación asistida por IA y validada por Pricing OS." : "Motor creado con la clasificación automática base."); }} />}
  </div>;
}

function EngineSources({ engine, pricing, assignments, onRefresh }: { engine: PricingEngine; pricing: PricingConfiguration; assignments: PricingConfiguration["engineSources"]; onRefresh: (message?: string) => Promise<void> }) {
  const [editing, setEditing] = useState(false);
  const [busy, setBusy] = useState(false);
  return <section className="engine-sources"><div className="config-toolbar"><div><span className="eyebrow">Fuentes para este motor</span><h3>{assignments.length} asignadas</h3><p>Una fuente global puede servir a varios motores sin duplicarse.</p></div><Button onClick={() => setEditing(!editing)}><Link2 size={15} /> {editing ? "Terminar" : "Administrar"}</Button></div>
    {assignments.length > 0 && <div className="engine-source-summary">{assignments.map((assignment) => { const source = pricing.marketSources.find((item) => item.id === assignment.sourceId); return source ? <div key={assignment.sourceId}><span><strong>{source.name}</strong><small>{assignment.role === "cost_input" ? "Costo directo" : assignment.role === "reference" ? "Referencia" : "Contexto"} · {assignment.preference === "preferred" ? "Preferida" : assignment.preference === "excluded" ? "Excluida" : "Disponible"}</small></span><b>{Math.round(assignment.matchScoreMicros / 10_000)}%</b></div> : null; })}</div>}
    {assignments.length === 0 && !editing && <div className="engine-source-empty">Todavía no hay fuentes asignadas. El motor puede calcular con datos manuales.</div>}
    {editing && <div className="engine-source-picker">{pricing.marketSources.map((source) => { const assignment = assignments.find((item) => item.sourceId === source.id); return <div key={source.id}><label><input type="checkbox" checked={Boolean(assignment)} disabled={busy} onChange={async (event) => { setBusy(true); try { if (!event.target.checked) await api.removeEngineSource(engine.id, source.id); else await api.saveEngineSource({ engineId: engine.id, sourceId: source.id, role: source.businessSourceType === "supplier" || source.businessSourceType === "internal" ? "cost_input" : source.usageMode === "market_price" ? "reference" : "context", preference: "available", participatesInSuggestions: source.participatesInSuggestions, matchScore: source.usageMode === "market_price" ? 0.8 : 0.65, explanation: `Fuente asignada a ${engine.name}.`, assignedBy: "manual" }); await onRefresh(); } finally { setBusy(false); } }} /><span><strong>{source.name}</strong><small>{source.purpose}</small></span></label>{assignment && <div className="engine-source-controls"><Select aria-label={`Rol de ${source.name}`} value={assignment.role} onChange={async (event) => { setBusy(true); try { await api.saveEngineSource({ engineId: engine.id, sourceId: source.id, role: event.target.value as typeof assignment.role, preference: assignment.preference, participatesInSuggestions: assignment.participatesInSuggestions, matchScore: assignment.matchScoreMicros / 1_000_000, explanation: assignment.explanation ?? undefined, assignedBy: "manual" }); await onRefresh(); } finally { setBusy(false); } }}><option value="reference">Referencia</option><option value="cost_input">Costo directo</option><option value="context">Contexto</option></Select><Select aria-label={`Preferencia de ${source.name}`} value={assignment.preference} onChange={async (event) => { setBusy(true); try { await api.saveEngineSource({ engineId: engine.id, sourceId: source.id, role: assignment.role, preference: event.target.value as typeof assignment.preference, participatesInSuggestions: assignment.participatesInSuggestions, matchScore: assignment.matchScoreMicros / 1_000_000, explanation: assignment.explanation ?? undefined, assignedBy: "manual" }); await onRefresh(); } finally { setBusy(false); } }}><option value="preferred">Preferida</option><option value="available">Disponible</option><option value="excluded">No usar</option></Select></div>}</div>; })}</div>}
  </section>;
}

function EngineWizard({ engine, pricing, onClose, onSaved }: { engine: PricingEngine | null; pricing: PricingConfiguration; onClose: () => void; onSaved: (engine: PricingEngine) => Promise<void> }) {
  const [form, setForm] = useState<ClassificationInput>({ name: engine?.name ?? "", description: engine?.description ?? "", deliverableKind: "unknown", activityKind: "unknown", pricingUnit: engine?.unitKind ?? "" });
  const [proposal, setProposal] = useState<ClassificationProposal | null>(engine ? { engineType: engine.engineType, categoryId: engine.categoryId, categoryPath: [], calculatorKey: engine.calculatorKey === "unconfigured" ? "professional-service-v1" : engine.calculatorKey, businessActivity: "Clasificación guardada", pricingUnits: [engine.unitKind], suggestedCostTypes: [], suggestedSourceTypes: [], tags: parseTags(engine.tagsJson), confidence: (engine.classificationConfidenceMicros ?? 0) / 1_000_000, explanation: engine.classificationExplanation ?? "", clarificationQuestion: null, aiAssisted: engine.classificationOrigin === "ai_assisted", aiError: null } : null);
  const [corrected, setCorrected] = useState(false);
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function analyze() { setBusy(true); setError(""); try { setProposal(await api.classifyPricingEngine(form)); } catch (reason) { setError(String(reason)); } finally { setBusy(false); } }
  async function save() {
    if (!proposal) return;
    setBusy(true); setError("");
    try {
      const input: PricingEngineInput = { id: engine?.id, name: form.name, description: form.description, engineType: proposal.engineType, categoryId: proposal.categoryId, calculatorKey: proposal.calculatorKey, unitKind: form.pricingUnit || proposal.pricingUnits[0] || "project", tags: proposal.tags, status: "active", classificationOrigin: corrected ? "manual" : proposal.aiAssisted ? "ai_assisted" : "automatic", classificationConfidence: proposal.confidence, classificationExplanation: corrected ? `${proposal.explanation} Clasificación corregida por el usuario.` : proposal.explanation };
      await onSaved(await api.savePricingEngine(input));
    } catch (reason) { setError(String(reason)); } finally { setBusy(false); }
  }
  return <Modal title={engine ? `Editar · ${engine.name}` : "Nuevo motor de pricing"} onClose={onClose} width="920px"><div className="modal__body engine-wizard"><div className="wizard-intro"><Sparkles size={20} /><div><strong>Contanos qué querés calcular</strong><span>La clasificación automática funciona siempre. Si activaste Ollama, sólo ayuda a interpretar esta descripción.</span></div></div><div className="form-grid"><Field label="Nombre de la actividad" hint="Ej.: Venta de remeras estampadas"><Input autoFocus value={form.name} onChange={(event) => { setForm({ ...form, name: event.target.value }); setProposal(null); }} /></Field><Field label="Unidad habitual" hint="Cómo solés cobrar o vender"><Input placeholder="unidad, docena, lote, proyecto…" value={form.pricingUnit} onChange={(event) => setForm({ ...form, pricingUnit: event.target.value })} /></Field><Field label="¿Qué entregás?" hint="Ayuda al clasificador cuando el nombre es ambiguo"><Select value={form.deliverableKind} onChange={(event) => { setForm({ ...form, deliverableKind: event.target.value as ClassificationInput["deliverableKind"] }); setProposal(null); }}><option value="unknown">Que lo detecte el programa</option><option value="physical">Producto físico</option><option value="digital">Entrega digital / servicio</option><option value="both">Ambas cosas</option></Select></Field><Field label="Actividad principal"><Select value={form.activityKind} onChange={(event) => { setForm({ ...form, activityKind: event.target.value as ClassificationInput["activityKind"] }); setProposal(null); }}><option value="unknown">Que lo detecte el programa</option><option value="sale">Producción o venta</option><option value="service">Servicio profesional</option><option value="both">Servicio + producto</option></Select></Field><Field label="Descripción breve" hint="Qué hacés, qué recibe el cliente y cómo lo vendés" className="span-2"><textarea className="input textarea" value={form.description} onChange={(event) => { setForm({ ...form, description: event.target.value }); setProposal(null); }} /></Field></div>
    {!proposal && <Button variant="accent" disabled={busy || !form.name.trim()} onClick={analyze}>{busy ? <RotateCcw className="spin" size={16} /> : <Sparkles size={16} />} Analizar actividad</Button>}
    {proposal && <div className="classification-proposal">
      <header><span className={`engine-kind engine-kind--${proposal.engineType}`}>{typeLabel[proposal.engineType]}</span><div><strong>{pricing.engineCategories.find((category) => category.id === proposal.categoryId)?.name || proposal.categoryPath.join(" → ") || "Categoría general"}</strong><small>{Math.round(proposal.confidence * 100)}% de confianza · {corrected ? "corregida por vos" : proposal.aiAssisted ? "IA local + validación" : "clasificador automático"}</small></div>{proposal.aiAssisted ? <Bot size={20} /> : <Check size={20} />}</header>
      <p>{proposal.explanation}</p>{proposal.clarificationQuestion && <div className="classification-question">{proposal.clarificationQuestion}</div>}{proposal.aiError && <div className="classification-fallback">La IA local no respondió: {proposal.aiError} Se utilizó la clasificación automática.</div>}
      <div className="classification-correction"><Field label="Tipo de motor" hint="Podés corregir lo que entendió el programa."><Select value={proposal.engineType} onChange={(event) => { const engineType = event.target.value as ClassificationProposal["engineType"]; const calculatorKey = engineType === "product" ? "physical-product-v1" : engineType === "hybrid" ? "hybrid-v1" : "professional-service-v1"; const category = pricing.engineCategories.find((item) => item.engineType === engineType); setProposal({ ...proposal, engineType, calculatorKey, categoryId: category?.id ?? null, categoryPath: category ? [category.name] : [] }); setCorrected(true); }}><option value="service">Servicio</option><option value="product">Producto</option><option value="hybrid">Híbrido</option></Select></Field><Field label="Categoría"><Select value={proposal.categoryId ?? ""} onChange={(event) => { const category = pricing.engineCategories.find((item) => item.id === event.target.value); setProposal({ ...proposal, categoryId: category?.id ?? null, categoryPath: category ? [category.name] : [] }); setCorrected(true); }}><option value="">Sin categoría</option>{pricing.engineCategories.filter((category) => category.engineType === proposal.engineType).map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</Select></Field></div>
      <div className="proposal-columns"><div><span>Costos que probablemente necesites</span><ul>{proposal.suggestedCostTypes.map((item) => <li key={item}>{item}</li>)}</ul></div><div><span>Fuentes que podrían servir</span><ul>{proposal.suggestedSourceTypes.map((item) => <li key={item}>{item}</li>)}</ul></div></div><div className="tag-list">{proposal.tags.map((tag) => <span key={tag}>{tag}</span>)}</div>
    </div>}
    {error && <div className="form-error" role="alert">{error}</div>}<div className="modal__actions"><Button onClick={onClose}>Cancelar</Button>{proposal && <Button variant="accent" disabled={busy} onClick={save}>{busy ? "Guardando…" : engine ? "Guardar cambios" : "Está bien · Crear motor"}</Button>}</div></div></Modal>;
}

function parseTags(value: string) { try { return JSON.parse(value) as string[]; } catch { return []; } }
