import { useEffect, useRef, useState } from "react";
import { Download, ImagePlus, RotateCcw, Save, ShieldCheck } from "lucide-react";
import type { BackupSummary, ProfessionalProfile, ProfessionalProfileInput } from "../../domain/types";
import { api } from "../../services/api";
import { Button, Field, Input, Select } from "../../components/ui";

function toInput(profile: ProfessionalProfile): ProfessionalProfileInput {
  return { displayName: profile.displayName, businessName: profile.businessName ?? "", email: profile.email ?? "", phone: profile.phone ?? "", website: profile.website ?? "", location: profile.location ?? "", logoDataUrl: profile.logoDataUrl, removeLogo: false, defaultCurrency: profile.defaultCurrency, defaultQuoteValidityDays: profile.defaultQuoteValidityDays, defaultClientTerms: profile.defaultClientTerms ?? "", documentTheme: profile.documentTheme };
}

export function ProfessionalSettings() {
  const [form, setForm] = useState<ProfessionalProfileInput | null>(null);
  const [status, setStatus] = useState("");
  const [error, setError] = useState("");
  const [backupContent, setBackupContent] = useState<string | null>(null);
  const [backupSummary, setBackupSummary] = useState<BackupSummary | null>(null);
  const logoInput = useRef<HTMLInputElement>(null);
  const backupInput = useRef<HTMLInputElement>(null);
  useEffect(() => { void api.getProfessionalProfile().then((profile) => setForm(toInput(profile))).catch((reason) => setError(String(reason))); }, []);
  const update = (next: Partial<ProfessionalProfileInput>) => setForm((current) => current ? { ...current, ...next } : current);
  async function save() { if (!form) return; setStatus("Guardando…"); setError(""); try { const saved = await api.saveProfessionalProfile(form); setForm(toInput(saved)); setStatus("Perfil profesional guardado."); } catch (reason) { setError(String(reason)); setStatus(""); } }
  function readLogo(file: File | undefined) { if (!file) return; if (file.size > 3_000_000) { setError("El logo no puede superar 3 MB."); return; } const reader = new FileReader(); reader.onload = () => update({ logoDataUrl: typeof reader.result === "string" ? reader.result : null, removeLogo: false }); reader.onerror = () => setError("No se pudo leer el logo seleccionado."); reader.readAsDataURL(file); }
  async function createBackup() { setStatus("Creando backup…"); setError(""); try { const output = await api.createPricingBackup(); setStatus(`Backup creado en: ${output.path}`); } catch (reason) { setError(String(reason)); setStatus(""); } }
  async function inspectBackup(file: File | undefined) { if (!file) return; setStatus("Validando backup…"); setError(""); try { const content = await file.text(); const summary = await api.inspectPricingBackup(content); setBackupContent(content); setBackupSummary(summary); setStatus("Backup válido. Revisá el resumen y confirmá la restauración."); } catch (reason) { setBackupContent(null); setBackupSummary(null); setError(String(reason)); setStatus(""); } }
  async function restore() { if (!backupContent || !backupSummary || !window.confirm("Se reemplazarán los datos actuales. Antes se creará un backup automático. ¿Continuar?")) return; setStatus("Restaurando…"); setError(""); try { const result = await api.restorePricingBackup(backupContent); setStatus(`Datos restaurados. Backup automático: ${result.automaticBackupPath}`); window.setTimeout(() => window.location.reload(), 900); } catch (reason) { setError(String(reason)); setStatus(""); } }
  if (!form) return <div className="settings-form"><section><p>{error || "Cargando perfil profesional…"}</p></section></div>;
  return <div className="settings-form professional-settings"><section><span className="eyebrow">Perfil reutilizable</span><h2>Datos profesionales</h2><p>Se usan únicamente en las cotizaciones externas; los cálculos internos no se comparten.</p><div className="form-grid"><Field label="Nombre profesional"><Input value={form.displayName} onChange={(event) => update({ displayName: event.target.value })} placeholder="Tu nombre" /></Field><Field label="Marca / estudio"><Input value={form.businessName ?? ""} onChange={(event) => update({ businessName: event.target.value })} /></Field><Field label="Email"><Input type="email" value={form.email ?? ""} onChange={(event) => update({ email: event.target.value })} /></Field><Field label="Teléfono"><Input value={form.phone ?? ""} onChange={(event) => update({ phone: event.target.value })} /></Field><Field label="Web"><Input value={form.website ?? ""} onChange={(event) => update({ website: event.target.value })} /></Field><Field label="Ubicación"><Input value={form.location ?? ""} onChange={(event) => update({ location: event.target.value })} /></Field><Field label="Moneda predeterminada"><Select value={form.defaultCurrency} onChange={(event) => update({ defaultCurrency: event.target.value as "USD" | "ARS" })}><option value="USD">USD</option><option value="ARS">ARS</option></Select></Field><Field label="Validez predeterminada"><Select value={form.defaultQuoteValidityDays ?? ""} onChange={(event) => update({ defaultQuoteValidityDays: event.target.value ? Number(event.target.value) as 7 | 15 | 30 : null })}><option value="">Sin vencimiento</option><option value="7">7 días</option><option value="15">15 días</option><option value="30">30 días</option></Select></Field><Field label="Modo del PDF"><Select value={form.documentTheme} onChange={(event) => update({ documentTheme: event.target.value as "light" | "dark" })}><option value="light">Claro · recomendado para impresión</option><option value="dark">Oscuro</option></Select></Field></div><Field label="Condiciones predeterminadas" hint="Texto público que podés cambiar en cada cotización."><textarea className="input textarea" rows={4} value={form.defaultClientTerms ?? ""} onChange={(event) => update({ defaultClientTerms: event.target.value })} /></Field><div className="profile-logo"><div>{form.logoDataUrl ? <img src={form.logoDataUrl} alt="Vista previa del logo" /> : <span>Sin logo</span>}</div><input ref={logoInput} className="sr-only" type="file" accept="image/png,image/jpeg" onChange={(event) => readLogo(event.target.files?.[0])} /><Button type="button" onClick={() => logoInput.current?.click()}><ImagePlus size={16} /> Elegir logo</Button>{form.logoDataUrl && <Button type="button" variant="ghost" onClick={() => update({ logoDataUrl: null, removeLogo: true })}>Quitar logo</Button>}</div><footer><span>{status}</span><Button variant="accent" onClick={() => void save()}><Save size={17} /> Guardar perfil</Button></footer></section>
    <section><span className="eyebrow">Resguardo local</span><h2>Backup y restauración</h2><p>Los backups se guardan como JSON versionado en Documentos/Pricing OS/Backups. Restaurar reemplaza los datos sólo después de validar el archivo y crear un resguardo automático.</p><div className="backup-actions"><Button onClick={() => void createBackup()}><Download size={16} /> Crear backup</Button><input ref={backupInput} className="sr-only" type="file" accept="application/json,.json" onChange={(event) => void inspectBackup(event.target.files?.[0])} /><Button onClick={() => backupInput.current?.click()}><RotateCcw size={16} /> Seleccionar backup</Button></div>{backupSummary && <div className="backup-summary"><ShieldCheck size={20} /><div><strong>Backup válido · esquema {backupSummary.schemaVersion}</strong><span>{backupSummary.clients} clientes · {backupSummary.quotes} cotizaciones · {backupSummary.sources} fuentes</span></div><Button variant="danger" onClick={() => void restore()}>Reemplazar datos</Button></div>}{error && <p className="form-error" role="alert">{error}</p>}{status && <p className="document-message" role="status">{status}</p>}</section></div>;
}
