import { useState } from "react";
import { Bot, BrainCircuit, Coins, Database, HelpCircle, Moon, Save, SlidersHorizontal, Sun, UserRound, Workflow } from "lucide-react";
import type { AppSettings, Currency, OllamaStatus, PricingConfiguration, SettingsInput } from "../../domain/types";
import { majorToMinor, minorToInput } from "../../domain/money";
import { api } from "../../services/api";
import { Button, Field, Input, Select } from "../../components/ui";
import { EconomySettings } from "./EconomySettings";
import { ServiceConfigurator } from "./ServiceConfigurator";
import { MarketSources } from "./MarketSources";
import { EngineManager } from "./EngineManager";
import { ProfessionalSettings } from "./ProfessionalSettings";

export type SettingsTab = "general" | "profile" | "economy" | "engines" | "rules" | "sources";

export function SettingsView({ settings, pricing, initialTab = "general", initialEconomyCurrency, initialEconomyEngineKey, onSave, onPricingChange }: { settings: AppSettings; pricing: PricingConfiguration; initialTab?: SettingsTab; initialEconomyCurrency?: Currency; initialEconomyEngineKey?: string; onSave: (input: SettingsInput) => Promise<void>; onPricingChange: (pricing: PricingConfiguration) => void }) {
  const [tab, setTab] = useState<SettingsTab>(initialTab);
  const apply = async (operation: Promise<PricingConfiguration>) => onPricingChange(await operation);
  return <div className="view-page settings-page settings-page--wide"><header className="page-header"><div><span className="eyebrow">Preferencias locales</span><h1>Configuración</h1><p>Motores, economía, fuentes y asistencia local en un sistema versionado.</p></div></header><nav className="settings-tabs" aria-label="Secciones de configuración"><button className={tab === "general" ? "is-active" : ""} onClick={() => setTab("general")}><SlidersHorizontal size={16} /> General</button><button className={tab === "profile" ? "is-active" : ""} onClick={() => setTab("profile")}><UserRound size={16} /> Perfil y datos</button><button className={tab === "economy" ? "is-active" : ""} onClick={() => setTab("economy")}><Coins size={16} /> Mi economía</button><button className={tab === "engines" ? "is-active" : ""} onClick={() => setTab("engines")}><Workflow size={16} /> Motores</button><button className={tab === "rules" ? "is-active" : ""} onClick={() => setTab("rules")}><Database size={16} /> Reglas</button><button className={tab === "sources" ? "is-active" : ""} onClick={() => setTab("sources")}><Database size={16} /> Fuentes</button></nav>
    {tab === "general" && <GeneralSettings settings={settings} onSave={onSave} />}
    {tab === "profile" && <ProfessionalSettings />}
    {tab === "economy" && <EconomySettings pricing={pricing} initialCurrency={initialEconomyCurrency} initialEngineKey={initialEconomyEngineKey} onSave={(input) => apply(api.saveEconomicProfile(input))} />}
    {tab === "engines" && <EngineManager pricing={pricing} onPricingChange={onPricingChange} />}
    {tab === "rules" && <ServiceConfigurator pricing={pricing} actions={{ saveDefinition: (input) => apply(api.saveServiceDefinition(input)), saveParameter: (input) => apply(api.saveServiceParameter(input)), deleteParameter: (id) => apply(api.deleteServiceParameter(id)), saveOption: (input) => apply(api.saveParameterOption(input)), deleteOption: (id) => apply(api.deleteParameterOption(id)), saveRule: (input) => apply(api.savePricingRule(input)), deleteRule: (id) => apply(api.deletePricingRule(id)) }} />}
    {tab === "sources" && <MarketSources pricing={pricing} onPricingChange={onPricingChange} />}
  </div>;
}

function GeneralSettings({ settings, onSave }: { settings: AppSettings; onSave: (input: SettingsInput) => Promise<void> }) {
  const [form, setForm] = useState({ theme: settings.theme, ars: minorToInput(settings.hourlyRateArsMinor), usd: minorToInput(settings.hourlyRateUsdMinor), fx: settings.usdToArsMicros ? String(settings.usdToArsMicros / 10_000) : "", suggestions: settings.suggestionsEnabled, strategy: settings.suggestionStrategy, baseCurrency: settings.baseCurrency, helpMode: settings.helpMode, localAi: settings.localAiEnabled, ollamaUrl: settings.ollamaBaseUrl, ollamaModel: settings.ollamaModel ?? "", aiAutoApply: settings.aiAutoApplyHighConfidence });
  const [status, setStatus] = useState("");
  const [ollama, setOllama] = useState<OllamaStatus | null>(null);
  const input = (): SettingsInput => ({ theme: form.theme, hourlyRateArsMinor: majorToMinor(form.ars), hourlyRateUsdMinor: majorToMinor(form.usd), usdToArsMicros: form.fx ? Math.round(Number(form.fx.replace(",", ".")) * 10_000) : null, suggestionsEnabled: form.suggestions, suggestionStrategy: form.strategy, baseCurrency: form.baseCurrency, helpMode: form.helpMode, localAiEnabled: form.localAi, ollamaBaseUrl: form.ollamaUrl, ollamaModel: form.ollamaModel || null, aiAutoApplyHighConfidence: form.aiAutoApply });
  async function submit(event: React.FormEvent) { event.preventDefault(); setStatus("Guardando…"); try { await onSave(input()); setStatus("Configuración guardada"); } catch (error) { setStatus(String(error)); } }
  async function testAi() { setStatus("Conectando con Ollama…"); try { await onSave(input()); const result = await api.testOllama(); setOllama(result); const selected = form.ollamaModel || result.models[0]?.name || ""; setForm((current) => ({ ...current, ollamaModel: selected })); setStatus(result.message); } catch (error) { setOllama(null); setStatus(String(error)); } }
  return <form className="settings-form" onSubmit={submit}><section><span className="eyebrow">Pricing</span><h2>Sugerencias y conversión</h2><p>Las fuentes aportan evidencia; el motor conserva siempre la decisión matemática.</p><div className="form-grid"><Field label="Cambio manual · 1 USD en ARS" hint="Convierte costos conservando su moneda original."><Input type="number" min="0.0001" step="0.0001" value={form.fx} onChange={(event) => setForm({ ...form, fx: event.target.value })} /></Field><Field label="Moneda base" hint="Moneda inicial para informes y costos internos."><Select value={form.baseCurrency} onChange={(event) => setForm({ ...form, baseCurrency: event.target.value as typeof form.baseCurrency })}><option value="USD">USD</option><option value="ARS">ARS</option></Select></Field><Field label="Estrategia sugerida" hint="Elige el margen objetivo; nunca reemplaza silenciosamente tu precio final."><Select disabled={!form.suggestions} value={form.strategy} onChange={(event) => setForm({ ...form, strategy: event.target.value as typeof form.strategy })}><option value="competitive">Competitiva</option><option value="balanced">Equilibrada</option><option value="premium">Premium</option></Select></Field><label className="check-label settings-toggle"><input type="checkbox" checked={form.suggestions} onChange={(event) => setForm({ ...form, suggestions: event.target.checked })} /><span><strong>Sugerencias {form.suggestions ? "ON" : "OFF"}</strong><small>Al apagar, los valores existentes permanecen intactos.</small></span></label></div></section>
    <section className="ai-settings"><span className="eyebrow">Clasificación de motores</span><h2>Automática primero · IA local opcional</h2><p>Pricing OS clasifica siempre mediante reglas, categorías y preguntas guiadas. Ollama sólo mejora la interpretación semántica de nombres y descripciones.</p><div className="automation-foundation"><BrainCircuit size={22} /><div><strong>Clasificador automático activo</strong><span>Funciona sin internet, sin Ollama y sin ningún modelo instalado.</span></div></div><div className="form-grid"><label className="check-label settings-toggle span-2"><input type="checkbox" checked={form.localAi} onChange={(event) => setForm({ ...form, localAi: event.target.checked })} /><span><strong>Mejorar clasificación con IA local {form.localAi ? "ON" : "OFF"}</strong><small>La IA no calcula precios, no modifica fórmulas y no elige fuentes definitivamente.</small></span></label><Field label="Dirección local de Ollama" hint="Por seguridad sólo se aceptan localhost, 127.0.0.1 o ::1."><Input disabled={!form.localAi} value={form.ollamaUrl} onChange={(event) => setForm({ ...form, ollamaUrl: event.target.value })} /></Field><Field label="Modelo" hint="Qwen 4B es suficiente para esta clasificación acotada.">{ollama?.models.length ? <Select disabled={!form.localAi} value={form.ollamaModel} onChange={(event) => setForm({ ...form, ollamaModel: event.target.value })}><option value="">Elegir modelo</option>{ollama.models.map((model) => <option key={model.name} value={model.name}>{model.name}{model.parameterSize ? ` · ${model.parameterSize}` : ""}</option>)}</Select> : <Input disabled={!form.localAi} placeholder="Ej. qwen3:4b" value={form.ollamaModel} onChange={(event) => setForm({ ...form, ollamaModel: event.target.value })} />}</Field><label className="check-label"><input disabled={!form.localAi} type="checkbox" checked={form.aiAutoApply} onChange={(event) => setForm({ ...form, aiAutoApply: event.target.checked })} /> Preseleccionar propuestas de confianza alta</label><Button type="button" disabled={!form.localAi} onClick={testAi}><Bot size={16} /> Probar conexión</Button></div>{ollama && <div className="ollama-result"><span className="status-dot status-dot--accent" /><strong>{ollama.message}</strong></div>}</section>
    <section><span className="eyebrow">Ayuda contextual</span><h2>Explicaciones de los campos</h2><div className="form-grid"><Field label="Nivel de ayuda" hint="Podés cambiarlo cuando ya conozcas el sistema."><Select value={form.helpMode} onChange={(event) => setForm({ ...form, helpMode: event.target.value as typeof form.helpMode })}><option value="guided">Guiada · explicación y efecto</option><option value="compact">Compacta · íconos de ayuda</option><option value="off">Desactivada</option></Select></Field><div className="help-mode-preview"><HelpCircle size={19} /><span>{form.helpMode === "guided" ? "Los campos muestran para qué sirven y cómo afectan el cálculo." : form.helpMode === "compact" ? "Las explicaciones aparecen al solicitarlas." : "Sólo se muestran etiquetas y validaciones necesarias."}</span></div></div></section>
    <section><span className="eyebrow">Apariencia</span><h2>Tema</h2><div className="theme-cards"><button type="button" className={form.theme === "warm" ? "is-active" : ""} onClick={() => setForm({ ...form, theme: "warm" })}><Sun size={22} /><strong>Warm Mode</strong><span>Marfil, tinta y rojo editorial.</span></button><button type="button" className={form.theme === "dark" ? "is-active" : ""} onClick={() => setForm({ ...form, theme: "dark" })}><Moon size={22} /><strong>Dark Mode</strong><span>Negro, blanco roto y rojo.</span></button></div></section><footer><span>{status}</span><Button variant="accent"><Save size={17} /> Guardar configuración</Button></footer></form>;
}
