import { useState } from "react";
import { Coins, Database, Moon, Save, SlidersHorizontal, Sun } from "lucide-react";
import type { AppSettings, PricingConfiguration, SettingsInput } from "../../domain/types";
import { majorToMinor, minorToInput } from "../../domain/money";
import { api } from "../../services/api";
import { Button, Field, Input, Select } from "../../components/ui";
import { EconomySettings } from "./EconomySettings";
import { ServiceConfigurator } from "./ServiceConfigurator";
import { MarketSources } from "./MarketSources";

type Tab = "general" | "economy" | "services" | "sources";

export function SettingsView({ settings, pricing, initialTab = "general", onSave, onPricingChange }: { settings: AppSettings; pricing: PricingConfiguration; initialTab?: Tab; onSave: (input: SettingsInput) => Promise<void>; onPricingChange: (pricing: PricingConfiguration) => void }) {
  const [tab, setTab] = useState<Tab>(initialTab);
  const apply = async (operation: Promise<PricingConfiguration>) => onPricingChange(await operation);
  return <div className="view-page settings-page settings-page--wide"><header className="page-header"><div><span className="eyebrow">Preferencias locales</span><h1>Configuración</h1><p>Economía, servicios, reglas y fuentes en un solo sistema versionado.</p></div></header><nav className="settings-tabs" aria-label="Secciones de configuración"><button className={tab === "general" ? "is-active" : ""} onClick={() => setTab("general")}><SlidersHorizontal size={16} /> General</button><button className={tab === "economy" ? "is-active" : ""} onClick={() => setTab("economy")}><Coins size={16} /> Mi economía</button><button className={tab === "services" ? "is-active" : ""} onClick={() => setTab("services")}><Database size={16} /> Servicios</button><button className={tab === "sources" ? "is-active" : ""} onClick={() => setTab("sources")}><Database size={16} /> Fuentes</button></nav>
    {tab === "general" && <GeneralSettings settings={settings} onSave={onSave} />}
    {tab === "economy" && <EconomySettings pricing={pricing} onSave={(input) => apply(api.saveEconomicProfile(input))} />}
    {tab === "services" && <ServiceConfigurator pricing={pricing} actions={{ saveDefinition: (input) => apply(api.saveServiceDefinition(input)), saveParameter: (input) => apply(api.saveServiceParameter(input)), deleteParameter: (id) => apply(api.deleteServiceParameter(id)), saveOption: (input) => apply(api.saveParameterOption(input)), deleteOption: (id) => apply(api.deleteParameterOption(id)), saveRule: (input) => apply(api.savePricingRule(input)), deleteRule: (id) => apply(api.deletePricingRule(id)) }} />}
    {tab === "sources" && <MarketSources pricing={pricing} onSave={(input) => apply(api.saveMarketSource(input))} onDelete={(id) => apply(api.deleteMarketSource(id))} onRestore={(id) => apply(api.restoreMarketSource(id))} />}
  </div>;
}

function GeneralSettings({ settings, onSave }: { settings: AppSettings; onSave: (input: SettingsInput) => Promise<void> }) {
  const [form, setForm] = useState({ theme: settings.theme, ars: minorToInput(settings.hourlyRateArsMinor), usd: minorToInput(settings.hourlyRateUsdMinor), fx: settings.usdToArsMicros ? String(settings.usdToArsMicros / 10_000) : "", suggestions: settings.suggestionsEnabled, strategy: settings.suggestionStrategy, baseCurrency: settings.baseCurrency });
  const [status, setStatus] = useState("");
  async function submit(event: React.FormEvent) { event.preventDefault(); setStatus("Guardando…"); try { await onSave({ theme: form.theme, hourlyRateArsMinor: majorToMinor(form.ars), hourlyRateUsdMinor: majorToMinor(form.usd), usdToArsMicros: form.fx ? Math.round(Number(form.fx.replace(",", ".")) * 10_000) : null, suggestionsEnabled: form.suggestions, suggestionStrategy: form.strategy, baseCurrency: form.baseCurrency }); setStatus("Configuración guardada"); } catch (error) { setStatus(String(error)); } }
  return <form className="settings-form" onSubmit={submit}><section><span className="eyebrow">Pricing</span><h2>Sugerencias y conversión</h2><p>Las sugerencias nunca reemplazan automáticamente el precio final. Los márgenes de cada estrategia se configuran por servicio.</p><div className="form-grid"><Field label="Cambio manual · 1 USD en ARS" hint="Sólo para conversiones explícitas."><Input type="number" min="0.0001" step="0.0001" value={form.fx} onChange={(e) => setForm({ ...form, fx: e.target.value })} /></Field><Field label="Moneda base"><Select value={form.baseCurrency} onChange={(e) => setForm({ ...form, baseCurrency: e.target.value as typeof form.baseCurrency })}><option value="USD">USD</option><option value="ARS">ARS</option></Select></Field><Field label="Estrategia sugerida"><Select disabled={!form.suggestions} value={form.strategy} onChange={(e) => setForm({ ...form, strategy: e.target.value as typeof form.strategy })}><option value="competitive">Competitiva</option><option value="balanced">Equilibrada</option><option value="premium">Premium</option></Select></Field><label className="check-label settings-toggle"><input type="checkbox" checked={form.suggestions} onChange={(e) => setForm({ ...form, suggestions: e.target.checked })} /><span><strong>Sugerencias {form.suggestions ? "ON" : "OFF"}</strong><small>Al apagar, los valores existentes permanecen intactos.</small></span></label></div></section><section><span className="eyebrow">Compatibilidad Fase 1</span><h2>Tarifas manuales rápidas</h2><p>Se sincronizan con la tarifa manual de Mi economía.</p><div className="form-grid"><Field label="Tarifa interna por hora · ARS"><Input type="number" min="0" step="0.01" value={form.ars} onChange={(e) => setForm({ ...form, ars: e.target.value })} /></Field><Field label="Tarifa interna por hora · USD"><Input type="number" min="0" step="0.01" value={form.usd} onChange={(e) => setForm({ ...form, usd: e.target.value })} /></Field></div></section><section><span className="eyebrow">Apariencia</span><h2>Tema</h2><div className="theme-cards"><button type="button" className={form.theme === "warm" ? "is-active" : ""} onClick={() => setForm({ ...form, theme: "warm" })}><Sun size={22} /><strong>Warm Mode</strong><span>Marfil, tinta y rojo editorial.</span></button><button type="button" className={form.theme === "dark" ? "is-active" : ""} onClick={() => setForm({ ...form, theme: "dark" })}><Moon size={22} /><strong>Dark Mode</strong><span>Negro, blanco roto y rojo.</span></button></div></section><footer><span>{status}</span><Button variant="accent"><Save size={17} /> Guardar configuración</Button></footer></form>;
}
