import { useState } from "react";
import { BarChart3, ChevronDown, Clock3, LineChart, Sparkles } from "lucide-react";
import type { Currency } from "../domain/types";
import type { ProjectResult } from "../domain/quote";
import { formatMoney, majorToMinor, minorToInput } from "../domain/money";
import { Button, Field, Input } from "./ui";

export function ResultInspector({ result, currency, activeServiceId, suggestionsEnabled, onFinalPriceChange }: { result: ProjectResult; currency: Currency; activeServiceId: string | null; suggestionsEnabled: boolean; onFinalPriceChange?: (finalMinor: number | null, reason: string | null) => void }) {
  const active = result.services.find(({ service }) => service.id === activeServiceId);
  const [breakdownOpen, setBreakdownOpen] = useState(false);
  const [overrideOpen, setOverrideOpen] = useState(Boolean(active?.result.hasOverride));
  const [finalInput, setFinalInput] = useState(() => minorToInput(active?.result.finalSubtotalMinor ?? null));
  const [reason, setReason] = useState(active?.service.manualReason ?? "");
  return <aside className="inspector"><section className="inspector__primary"><span className="eyebrow">Resultado</span><div className="hero-price"><small>{result.isPartial ? "Subtotal parcial" : "Total del proyecto"}</small><strong>{formatMoney(result.totalMinor, currency)}</strong></div>{result.services.length === 0 && <p className="inspector__message">Agregá un servicio para comenzar la cotización.</p>}{result.unpricedCount > 0 && <p className="inspector__message">{result.unpricedCount} {result.unpricedCount === 1 ? "servicio pendiente de precio" : "servicios pendientes de precio"}.</p>}
    {active && <div className="pricing-stack"><div className="price-row"><span>Calculado</span><strong>{formatMoney(active.result.calculatedSubtotalMinor, currency)}</strong></div>{suggestionsEnabled && <div className="price-row price-row--suggested"><span>Sugerido</span><strong>{formatMoney(active.result.suggestedSubtotalMinor, currency)}</strong></div>}<div className="price-row price-row--final"><span>Precio final</span><strong>{formatMoney(active.result.finalSubtotalMinor, currency)}</strong></div>{active.result.issues.length > 0 && <div className="pricing-issues">{active.result.issues.map((issue) => <p key={issue}>{issue}</p>)}</div>}
      <label className="override-toggle"><input type="checkbox" checked={overrideOpen} onChange={(e) => { setOverrideOpen(e.target.checked); if (!e.target.checked) onFinalPriceChange?.(null, null); }} /> Definir precio final manual</label>{overrideOpen && <div className="override-box"><Field label={`Precio final · ${currency}`}><Input type="number" min="0" step="0.01" value={finalInput} onChange={(e) => setFinalInput(e.target.value)} /></Field><Field label="Motivo · opcional"><Input value={reason} onChange={(e) => setReason(e.target.value)} /></Field><Button variant="accent" onClick={() => onFinalPriceChange?.(majorToMinor(finalInput), reason || null)}>Aplicar precio final</Button></div>}
      <button className={`breakdown-toggle ${breakdownOpen ? "is-open" : ""}`} onClick={() => setBreakdownOpen(!breakdownOpen)}>Ver desglose <ChevronDown size={16} /></button>{breakdownOpen && <div className="breakdown">{active.result.lines.length === 0 ? <p>El servicio todavía no tiene líneas calculables.</p> : active.result.lines.map((line, index) => <div key={`${line.id ?? line.label}-${index}`}><span>{line.label}<small>{line.detail}</small></span><strong>{line.amountMinor >= 0 ? "+" : "−"}{formatMoney(Math.abs(line.amountMinor), currency)}</strong></div>)}</div>}
    </div>}
    <div className="metric"><Clock3 size={19} /><span>Horas estimadas</span><strong>{result.totalHours > 0 ? `${result.totalHours.toLocaleString("es-AR")} h` : "—"}</strong></div><div className="metric"><BarChart3 size={19} /><span>Valor efectivo / h</span><strong>{formatMoney(result.effectiveHourlyMinor, currency)}</strong></div></section><section className="market-panel"><span className="eyebrow">Referencia de mercado</span><div className="future-badge"><Sparkles size={18} /><div><strong>Fuentes registradas</strong><span>Sin extracción automática</span></div></div><p>Fase 2 administra fuentes y metodología, pero no inventa ni descarga rangos.</p><button disabled><LineChart size={17} /> Investigación futura</button></section></aside>;
}
