import { useState } from "react";
import { ArrowUpRight, BarChart3, ChevronDown, Clock3, LineChart, RefreshCw, XCircle } from "lucide-react";
import type { Currency, MarketObservation, MarketOverview, MarketResearchJob } from "../domain/types";
import type { ProjectResult } from "../domain/quote";
import { formatMoney, majorToMinor, minorToInput } from "../domain/money";
import { api } from "../services/api";
import { Button, Field, Input, Modal } from "./ui";

export function ResultInspector({ result, currency, activeServiceId, suggestionsEnabled, market, marketJob, onUpdateMarket, onCancelMarket, onFinalPriceChange }: { result: ProjectResult; currency: Currency; activeServiceId: string | null; suggestionsEnabled: boolean; market: MarketOverview | null; marketJob: MarketResearchJob | null; onUpdateMarket: (force?: boolean) => Promise<void>; onCancelMarket: () => Promise<void>; onFinalPriceChange?: (finalMinor: number | null, reason: string | null) => void }) {
  const active = result.services.find(({ service }) => service.id === activeServiceId);
  const [breakdownOpen, setBreakdownOpen] = useState(false);
  const [overrideOpen, setOverrideOpen] = useState(Boolean(active?.result.hasOverride));
  const [finalInput, setFinalInput] = useState(() => minorToInput(active?.result.finalSubtotalMinor ?? null));
  const [reason, setReason] = useState(active?.service.manualReason ?? "");
  const [sourcesOpen, setSourcesOpen] = useState(false);
  const [explanationOpen, setExplanationOpen] = useState(false);
  return <aside className="inspector"><section className="inspector__primary"><span className="eyebrow">Resultado</span><div className="hero-price"><small>{result.isPartial ? "Subtotal parcial" : "Total del proyecto"}</small><strong>{formatMoney(result.totalMinor, currency)}</strong></div>{result.services.length === 0 && <p className="inspector__message">Agregá un servicio para comenzar la cotización.</p>}{result.unpricedCount > 0 && <p className="inspector__message">{result.unpricedCount} {result.unpricedCount === 1 ? "servicio pendiente de precio" : "servicios pendientes de precio"}.</p>}
    {active && <div className="pricing-stack"><div className="price-row"><span>Calculado</span><strong>{formatMoney(active.result.calculatedSubtotalMinor, currency)}</strong></div>{suggestionsEnabled && <div className="price-row price-row--suggested"><span>Sugerido</span><strong>{formatMoney(active.result.suggestedSubtotalMinor, currency)}</strong></div>}<div className="price-row price-row--final"><span>Precio final</span><strong>{formatMoney(active.result.finalSubtotalMinor, currency)}</strong></div>{active.result.issues.length > 0 && <div className="pricing-issues">{active.result.issues.map((issue) => <p key={issue}>{issue}</p>)}</div>}
      <label className="override-toggle"><input type="checkbox" checked={overrideOpen} onChange={(e) => { setOverrideOpen(e.target.checked); if (!e.target.checked) onFinalPriceChange?.(null, null); }} /> Definir precio final manual</label>{overrideOpen && <div className="override-box"><Field label={`Precio final · ${currency}`}><Input type="number" min="0" step="0.01" value={finalInput} onChange={(e) => setFinalInput(e.target.value)} /></Field><Field label="Motivo · opcional"><Input value={reason} onChange={(e) => setReason(e.target.value)} /></Field><Button variant="accent" onClick={() => onFinalPriceChange?.(majorToMinor(finalInput), reason || null)}>Aplicar precio final</Button></div>}
      <button type="button" className={`breakdown-toggle ${breakdownOpen ? "is-open" : ""}`} aria-expanded={breakdownOpen} onClick={() => setBreakdownOpen(!breakdownOpen)}>Ver desglose <ChevronDown size={16} aria-hidden="true" /></button>{breakdownOpen && <div className="breakdown">{active.result.lines.length === 0 ? <p>El servicio todavía no tiene líneas calculables.</p> : active.result.lines.map((line, index) => <div key={`${line.id ?? line.label}-${index}`}><span>{line.label}<small>{line.detail}</small></span><strong>{line.amountMinor >= 0 ? "+" : "−"}{formatMoney(Math.abs(line.amountMinor), currency)}</strong></div>)}</div>}
    </div>}
    <div className="metric"><Clock3 size={19} /><span>Horas estimadas</span><strong>{result.totalHours > 0 ? `${result.totalHours.toLocaleString("es-AR")} h` : "—"}</strong></div><div className="metric"><BarChart3 size={19} /><span>Valor efectivo / h</span><strong>{formatMoney(result.effectiveHourlyMinor, currency)}</strong></div></section><MarketPanel active={Boolean(active)} currency={currency} market={market} job={marketJob} onUpdate={onUpdateMarket} onCancel={onCancelMarket} onSources={() => setSourcesOpen(true)} onExplain={() => setExplanationOpen(true)} />
    {sourcesOpen && <MarketEvidenceModal market={market} currency={currency} onClose={() => setSourcesOpen(false)} />}
    {explanationOpen && <SuggestionExplanationModal market={market} currency={currency} onClose={() => setExplanationOpen(false)} />}
  </aside>;
}

function MarketPanel({ active, currency, market, job, onUpdate, onCancel, onSources, onExplain }: { active: boolean; currency: Currency; market: MarketOverview | null; job: MarketResearchJob | null; onUpdate: (force?: boolean) => Promise<void>; onCancel: () => Promise<void>; onSources: () => void; onExplain: () => void }) {
  const snapshot = market?.latestSnapshot;
  const running = job?.status === "RUNNING";
  return <section className="market-panel"><span className="eyebrow">Referencia de mercado</span>
    {running && job ? <div className="inspector-research"><div><RefreshCw className="spin" size={17} /><strong>Actualizando mercado</strong><span>{job.completed} / {job.total} fuentes</span></div>{job.items.map((item) => <p key={item.sourceId}><span>{item.sourceName}</span><b>{item.status}</b></p>)}<Button variant="danger" onClick={onCancel}><XCircle size={15} /> Cancelar</Button></div>
      : snapshot ? <>{job?.error && <p className="market-offline">{job.error}</p>}<div className="market-range"><small>Rango comparable</small><strong>{snapshot.minimumFilteredMinor == null ? "Datos insuficientes" : `${formatMoney(snapshot.minimumFilteredMinor, currency)} — ${formatMoney(snapshot.maximumFilteredMinor, currency)}`}</strong></div><div className="market-median"><span>Mediana</span><b>{formatMoney(snapshot.marketMedianMinor, currency)}</b></div><div className="market-confidence"><span>Confianza</span><b>{snapshot.confidenceLevel.toLocaleLowerCase("es-AR")}</b><small>{snapshot.comparableObservationCount} observaciones · {snapshot.sourceCount} fuentes</small></div><p className="market-updated">Actualizado {relative(snapshot.createdAt)}</p><div className="market-panel__actions"><Button onClick={onSources}>Ver fuentes</Button><Button onClick={() => onUpdate(false)}><RefreshCw size={15} /> Actualizar</Button><button className="text-action" onClick={onExplain}>¿Por qué este precio?</button><button className="text-action" onClick={() => { if (window.confirm("¿Forzar una actualización ignorando el cooldown de las fuentes?")) void onUpdate(true); }}>Forzar actualización</button></div></>
      : <div className="market-empty-state"><LineChart size={24} /><strong>Todavía no hay datos</strong><p>La investigación sólo comienza cuando vos la pedís.</p><Button variant="accent" disabled={!active} onClick={() => onUpdate(false)}>Actualizar mercado</Button></div>}
  </section>;
}

function MarketEvidenceModal({ market, onClose }: { market: MarketOverview | null; currency: Currency; onClose: () => void }) {
  return <Modal title="Fuentes utilizadas" onClose={onClose} width="1080px"><div className="modal__body observations-modal">{!market?.observations.length ? <p>No hay observaciones en este snapshot.</p> : <div className="observation-table" role="table" aria-label="Evidencia utilizada en el snapshot" tabIndex={0}><div className="observation-row observation-row--head" role="row"><span role="columnheader">Fuente</span><span role="columnheader">Servicio</span><span role="columnheader">Precio</span><span role="columnheader">Unidad</span><span role="columnheader">Fecha</span><span role="columnheader">Comparable</span></div>{market.observations.map((row) => {
    const included = row.snapshotIncluded ?? row.comparisonEligibility === "ELIGIBLE";
    const reason = row.snapshotExclusionReason || row.exclusionReason;
    return <div className="observation-row" role="row" key={row.id}><span role="cell"><strong>{row.sourceName}</strong><small>{row.sourceType.replaceAll("_", " ")}</small></span><span role="cell">{row.subservice || row.serviceType}<small>{row.region}</small></span><span role="cell">{observationPrice(row)}{row.convertedValueMinor != null && row.convertedCurrency && <small>Convertido: {money(row.convertedValueMinor, row.convertedCurrency)} · tasa {row.exchangeRateMicros == null ? "—" : (row.exchangeRateMicros / 10_000).toLocaleString("es-AR")} · {row.exchangeRateDate || "sin fecha"}</small>}</span><span role="cell">{row.priceType}<small>{row.unit}</small></span><span role="cell">{new Date(row.publishedAt || row.retrievedAt).toLocaleDateString("es-AR")}</span><span role="cell"><b>{included ? "Sí" : "No"}</b><small>{reason}</small><button type="button" className="source-link-button" onClick={() => apiOpen(row.sourceUrl)}>Original <ArrowUpRight size={13} aria-hidden="true" /></button></span></div>;
  })}</div>}<div className="modal__actions"><Button onClick={onClose}>Cerrar</Button></div></div></Modal>;
}

function SuggestionExplanationModal({ market, currency, onClose }: { market: MarketOverview | null; currency: Currency; onClose: () => void }) {
  const snapshot = market?.latestSnapshot; let summary: { strategy?: string; suggestionExplanation?: string; explanations?: string[] } = {}; try { summary = snapshot ? JSON.parse(snapshot.summaryJson) as typeof summary : {}; } catch { /* snapshot legacy */ }
  return <Modal title="¿Por qué este precio?" onClose={onClose} width="680px"><div className="modal__body suggestion-explanation">{snapshot ? <><div><span>Tu cálculo</span><strong>{formatMoney(snapshot.calculatedPriceMinor, currency)}</strong></div><div><span>Mercado comparable</span><strong>{snapshot.minimumFilteredMinor == null ? "Insuficiente" : `${formatMoney(snapshot.minimumFilteredMinor, currency)} — ${formatMoney(snapshot.maximumFilteredMinor, currency)}`}</strong></div><div><span>Mediana</span><strong>{formatMoney(snapshot.marketMedianMinor, currency)}</strong></div><div><span>Estrategia</span><strong>{summary.strategy?.replace("balanced", "equilibrada") ?? "—"}</strong></div><div className="suggestion-explanation__result"><span>Precio sugerido</span><strong>{formatMoney(snapshot.suggestedPriceMinor, currency)}</strong></div><p>{summary.suggestionExplanation}</p><ul>{summary.explanations?.map((item) => <li key={item}>{item}</li>)}</ul><small>El precio final permaneció protegido y no fue modificado por esta investigación.</small></> : <p>No existe un snapshot para explicar.</p>}<div className="modal__actions"><Button onClick={onClose}>Cerrar</Button></div></div></Modal>;
}

function observationPrice(row: MarketObservation) { if (row.priceValueMinor != null) return money(row.priceValueMinor, row.currency); const minimum = row.priceMinMinor == null ? "—" : money(row.priceMinMinor, row.currency); const maximum = row.priceMaxMinor == null ? "—" : money(row.priceMaxMinor, row.currency); return `${minimum} — ${maximum}`; }
function money(value: number, currency: string) { try { return new Intl.NumberFormat("es-AR", { style: "currency", currency, maximumFractionDigits: 2 }).format(value / 100); } catch { return `${currency} ${(value / 100).toLocaleString("es-AR")}`; } }
function apiOpen(url: string) { void api.openMarketSource(url); }
function relative(raw: string) { const hours = Math.max(0, Math.floor((Date.now() - new Date(raw).getTime()) / 3_600_000)); return hours < 1 ? "hace menos de 1 h" : hours < 48 ? `hace ${hours} h` : `el ${new Date(raw).toLocaleDateString("es-AR")}`; }
