import { useMemo, useState } from "react";
import { Archive, Edit3, Plus, RotateCcw, Search } from "lucide-react";
import type { Client, ClientInput, ProjectSummary } from "../../domain/types";
import { Button, EmptyState, Field, Input, Modal } from "../../components/ui";

function ClientModal({ client, onClose, onSave }: { client: Client | null; onClose: () => void; onSave: (input: ClientInput) => Promise<void> }) {
  const [form, setForm] = useState<ClientInput>({ id: client?.id, name: client?.name ?? "", company: client?.company ?? "", email: client?.email ?? "", whatsapp: client?.whatsapp ?? "", country: client?.country ?? "", notes: client?.notes ?? "" });
  const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  async function submit(event: React.FormEvent) { event.preventDefault(); if (!form.name.trim()) return setError("El nombre es obligatorio."); setSaving(true); try { await onSave(form); onClose(); } catch (reason) { setError(String(reason)); } finally { setSaving(false); } }
  const patch = (key: keyof ClientInput, value: string) => setForm((current) => ({ ...current, [key]: value }));
  return <Modal title={client ? "Editar cliente" : "Nuevo cliente"} onClose={onClose}><form className="modal__body form-stack" onSubmit={submit}><div className="form-grid"><Field label="Nombre"><Input autoFocus value={form.name} onChange={(event) => patch("name", event.target.value)} /></Field><Field label="Empresa"><Input value={form.company} onChange={(event) => patch("company", event.target.value)} /></Field><Field label="Email"><Input type="email" value={form.email} onChange={(event) => patch("email", event.target.value)} /></Field><Field label="WhatsApp"><Input value={form.whatsapp} onChange={(event) => patch("whatsapp", event.target.value)} /></Field><Field label="País"><Input value={form.country} onChange={(event) => patch("country", event.target.value)} /></Field><Field label="Notas"><Input value={form.notes} onChange={(event) => patch("notes", event.target.value)} /></Field></div>{error && <div className="form-error">{error}</div>}<footer className="modal__actions"><Button type="button" variant="ghost" onClick={onClose}>Cancelar</Button><Button variant="accent" disabled={saving}>{saving ? "Guardando…" : "Guardar cliente"}</Button></footer></form></Modal>;
}

export function ClientsView({ clients, projects, onSave, onArchive, onOpenProject }: { clients: Client[]; projects: ProjectSummary[]; onSave: (input: ClientInput) => Promise<void>; onArchive: (client: Client, archived: boolean) => Promise<void>; onOpenProject: (id: string) => void }) {
  const [search, setSearch] = useState(""); const [showArchived, setShowArchived] = useState(false); const [modalClient, setModalClient] = useState<Client | null | undefined>(undefined);
  const filtered = useMemo(() => clients.filter((client) => (showArchived || client.status === "active") && `${client.name} ${client.company ?? ""} ${client.email ?? ""}`.toLowerCase().includes(search.toLowerCase())), [clients, search, showArchived]);
  return <div className="view-page"><header className="page-header"><div><span className="eyebrow">Directorio</span><h1>Clientes</h1><p>Un cliente puede reunir múltiples proyectos sin duplicarse.</p></div><Button variant="accent" onClick={() => setModalClient(null)}><Plus size={17} /> Nuevo cliente</Button></header><div className="list-toolbar"><label className="search-box"><Search size={17} /><input aria-label="Buscar clientes" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Buscar cliente, empresa o email" /></label><label className="check-label"><input type="checkbox" checked={showArchived} onChange={(event) => setShowArchived(event.target.checked)} /> Mostrar archivados</label></div>{filtered.length === 0 ? <EmptyState title="No hay clientes para mostrar" description="Creá un cliente o ajustá la búsqueda." action={<Button onClick={() => setModalClient(null)}>Crear cliente</Button>} /> : <div className="editorial-table"><div className="editorial-table__head client-columns"><span>Cliente</span><span>Contacto</span><span>Proyectos asociados</span><span>Estado</span><span /></div>{filtered.map((client) => { const related = projects.filter((project) => project.clientId === client.id); return <div className="editorial-table__row client-columns" key={client.id}><div><strong>{client.name}</strong><small>{client.company || "Profesional independiente"}</small></div><div><span>{client.email || "Sin email"}</span><small>{client.whatsapp || client.country || "Sin datos adicionales"}</small></div><div className="related-projects">{related.length === 0 ? <small>Sin proyectos</small> : related.slice(0,2).map((project) => <button key={project.id} onClick={() => onOpenProject(project.id)}>{project.name}</button>)}</div><span className={`state-label state-label--${client.status}`}>{client.status === "active" ? "Activo" : "Archivado"}</span><div className="row-actions"><button title="Editar" onClick={() => setModalClient(client)}><Edit3 size={16} /></button><button title={client.status === "active" ? "Archivar" : "Restaurar"} onClick={() => onArchive(client, client.status === "active")}>{client.status === "active" ? <Archive size={16} /> : <RotateCcw size={16} />}</button></div></div>; })}</div>}{modalClient !== undefined && <ClientModal client={modalClient} onClose={() => setModalClient(undefined)} onSave={onSave} />}</div>;
}
